// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/unkeyed/sdks/api/go/v3/internal/utils"
)

// SourceType - The configured source used to create deployments. Omitted for historical
// apps whose source could not be classified.
type SourceType string

const (
	SourceTypeGit SourceType = "git"
	SourceTypeOci SourceType = "oci"
)

func (e SourceType) ToPointer() *SourceType {
	return &e
}
func (e *SourceType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "git":
		fallthrough
	case "oci":
		*e = SourceType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for SourceType: %v", v)
	}
}

type App struct {
	// The unique identifier of the app, generated by Unkey.
	//
	ID string `json:"id"`
	// Human-readable name for this app.
	//
	Name string `json:"name"`
	// URL-safe handle for this app, unique within its project.
	// Chosen at creation time.
	//
	Slug string `json:"slug"`
	// The configured source used to create deployments. Omitted for historical
	// apps whose source could not be classified.
	//
	SourceType *SourceType `json:"sourceType,omitzero"`
	// The connected GitHub repository and the branch its deployments track.
	// Omitted when the app has no repository connected (for example a
	// prebuilt OCI image app).
	//
	Git *AppGit `json:"git,omitzero"`
	// The configured OCI image source. Omitted when the app is not OCI-sourced.
	//
	Oci *AppOCI `json:"oci,omitzero"`
	// The identifier of the deployment currently serving this app.
	// Omitted if the app has no active deployment yet.
	//
	CurrentDeploymentID *string `json:"currentDeploymentId,omitzero"`
	// Whether the app is currently serving a rolled-back deployment rather than its latest one.
	//
	IsRolledBack bool `json:"isRolledBack"`
	// Whether delete protection is enabled for this app.
	// When true, the app cannot be deleted until protection is disabled.
	//
	DeleteProtection bool `json:"deleteProtection"`
	// Unix timestamp in milliseconds when the app was created.
	//
	CreatedAt int64 `json:"createdAt"`
	// Unix timestamp in milliseconds when the app was last updated.
	// Omitted if the app has never been updated.
	//
	UpdatedAt *int64 `json:"updatedAt,omitzero"`
}

func (a App) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *App) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *App) GetID() string {
	if a == nil {
		return ""
	}
	return a.ID
}

func (a *App) GetName() string {
	if a == nil {
		return ""
	}
	return a.Name
}

func (a *App) GetSlug() string {
	if a == nil {
		return ""
	}
	return a.Slug
}

func (a *App) GetSourceType() *SourceType {
	if a == nil {
		return nil
	}
	return a.SourceType
}

func (a *App) GetGit() *AppGit {
	if a == nil {
		return nil
	}
	return a.Git
}

func (a *App) GetOci() *AppOCI {
	if a == nil {
		return nil
	}
	return a.Oci
}

func (a *App) GetCurrentDeploymentID() *string {
	if a == nil {
		return nil
	}
	return a.CurrentDeploymentID
}

func (a *App) GetIsRolledBack() bool {
	if a == nil {
		return false
	}
	return a.IsRolledBack
}

func (a *App) GetDeleteProtection() bool {
	if a == nil {
		return false
	}
	return a.DeleteProtection
}

func (a *App) GetCreatedAt() int64 {
	if a == nil {
		return 0
	}
	return a.CreatedAt
}

func (a *App) GetUpdatedAt() *int64 {
	if a == nil {
		return nil
	}
	return a.UpdatedAt
}
