// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AppGit struct {
	// The connected GitHub repository, as "owner/repo".
	Repository string `json:"repository"`
	// The branch this app's deployments track.
	DefaultBranch *string `json:"defaultBranch,omitzero"`
}

func (a *AppGit) GetRepository() string {
	if a == nil {
		return ""
	}
	return a.Repository
}

func (a *AppGit) GetDefaultBranch() *string {
	if a == nil {
		return nil
	}
	return a.DefaultBranch
}
