// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/unkeyed/sdks/api/go/v3/internal/utils"
)

// AppOCI - An app's OCI image source.
type AppOCI struct {
	// The configured default OCI image reference for new deployments. It must include an explicit tag or digest.
	Image string `json:"image"`
}

func (a AppOCI) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AppOCI) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, []string{"image"}); err != nil {
		return err
	}
	return nil
}

func (a *AppOCI) GetImage() string {
	if a == nil {
		return ""
	}
	return a.Image
}
