// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// AuthenticatedSubjectKey - Rate limit by the authenticated subject (e.g. the verified key).
type AuthenticatedSubjectKey struct {
}
