// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type DeploymentGitAuthor struct {
	// The GitHub login, or the handle the client sent.
	Handle string `json:"handle"`
	// The avatar URL for `handle`. Omitted when unknown.
	AvatarURL *string `json:"avatarUrl,omitzero"`
}

func (d *DeploymentGitAuthor) GetHandle() string {
	if d == nil {
		return ""
	}
	return d.Handle
}

func (d *DeploymentGitAuthor) GetAvatarURL() *string {
	if d == nil {
		return nil
	}
	return d.AvatarURL
}
