// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// EnvironmentBuild - Build settings that control how the app is built.
// Omitted until the environment has build settings.
type EnvironmentBuild struct {
	// Path to the Dockerfile used to build the app, if any.
	//
	Dockerfile *string `json:"dockerfile,omitzero"`
	// The directory the app is built from. "." for the repository root.
	//
	RootDirectory string `json:"rootDirectory"`
	// Overrides the build command auto-detected by Railpack, so monorepos can
	// scope the build to a single app. Omitted when left to auto-detection or
	// for Dockerfile builds.
	//
	BuildCommand *string `json:"buildCommand,omitzero"`
	// Paths that trigger a rebuild when changed.
	//
	WatchPaths []string `json:"watchPaths"`
	// Whether pushes automatically trigger a deployment.
	//
	AutoDeploy bool `json:"autoDeploy"`
}

func (e *EnvironmentBuild) GetDockerfile() *string {
	if e == nil {
		return nil
	}
	return e.Dockerfile
}

func (e *EnvironmentBuild) GetRootDirectory() string {
	if e == nil {
		return ""
	}
	return e.RootDirectory
}

func (e *EnvironmentBuild) GetBuildCommand() *string {
	if e == nil {
		return nil
	}
	return e.BuildCommand
}

func (e *EnvironmentBuild) GetWatchPaths() []string {
	if e == nil {
		return []string{}
	}
	return e.WatchPaths
}

func (e *EnvironmentBuild) GetAutoDeploy() bool {
	if e == nil {
		return false
	}
	return e.AutoDeploy
}
