// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// IdentityMeta - Identity metadata
type IdentityMeta struct {
}

type Identity struct {
	// External identity ID
	ExternalID string `json:"externalId"`
	// Identity metadata
	Meta        *IdentityMeta       `json:"meta,omitempty"`
	Ratelimits  []RatelimitResponse `json:"ratelimits"`
	Description any                 `json:"description,omitempty"`
}

func (o *Identity) GetExternalID() string {
	if o == nil {
		return ""
	}
	return o.ExternalID
}

func (o *Identity) GetMeta() *IdentityMeta {
	if o == nil {
		return nil
	}
	return o.Meta
}

func (o *Identity) GetRatelimits() []RatelimitResponse {
	if o == nil {
		return []RatelimitResponse{}
	}
	return o.Ratelimits
}

func (o *Identity) GetDescription() any {
	if o == nil {
		return nil
	}
	return o.Description
}
