// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type IdentitiesCreateIdentityResponseData struct {
	// The id of the identity. Used internally, you do not need to store this.
	IdentityID string `json:"identityId"`
}

func (o *IdentitiesCreateIdentityResponseData) GetIdentityID() string {
	if o == nil {
		return ""
	}
	return o.IdentityID
}
