// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// KeysVerifyKeyCredits - Controls credit consumption for usage-based billing and quota enforcement.
// Omitting this field uses the default cost of 1 credit per verification.
// Credits provide globally consistent usage tracking, essential for paid APIs with strict quotas.
type KeysVerifyKeyCredits struct {
	// Sets how many credits to deduct for this verification request.
	// Use 0 for read-only operations or free tier access, higher values for premium features.
	// Credits are deducted after all security checks pass.
	// Essential for implementing usage-based pricing with different operation costs.
	//
	Cost int `json:"cost"`
}

func (o *KeysVerifyKeyCredits) GetCost() int {
	if o == nil {
		return 0
	}
	return o.Cost
}
