// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/unkeyed/sdks/api/go/v3/internal/utils"
)

// LoggingPolicy - Adds request data to the log entries of matching requests. The gateway
// always records a basic log entry for every request: method, host, path,
// status, and latency. Each capture setting is a separate opt-in: request
// headers, response headers, request body, response body, and query data.
// The policy's `match` expressions select the requests. A policy without
// `match` expressions matches every request. If more than one enabled
// logging policy matches a request, the gateway combines their settings.
// The gateway always redacts the `Authorization` header and configured key
// locations before it stores headers or query data.
type LoggingPolicy struct {
	// Capture request headers, the user agent, and the client IP. The user
	// agent and client IP are included because they identify the client.
	RequestHeaders *bool `default:"false" json:"requestHeaders"`
	// Capture response headers.
	ResponseHeaders *bool `default:"false" json:"responseHeaders"`
	// Capture the request body, up to the capture limit.
	RequestBody *bool `default:"false" json:"requestBody"`
	// Capture the response body, up to the capture limit.
	ResponseBody *bool `default:"false" json:"responseBody"`
	// Capture the query string and query parameters. Query data is a
	// separate opt-in because URLs can contain secrets, for example
	// `?api_key=...`.
	Query *bool `default:"false" json:"query"`
}

func (l LoggingPolicy) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *LoggingPolicy) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *LoggingPolicy) GetRequestHeaders() *bool {
	if l == nil {
		return nil
	}
	return l.RequestHeaders
}

func (l *LoggingPolicy) GetResponseHeaders() *bool {
	if l == nil {
		return nil
	}
	return l.ResponseHeaders
}

func (l *LoggingPolicy) GetRequestBody() *bool {
	if l == nil {
		return nil
	}
	return l.RequestBody
}

func (l *LoggingPolicy) GetResponseBody() *bool {
	if l == nil {
		return nil
	}
	return l.ResponseBody
}

func (l *LoggingPolicy) GetQuery() *bool {
	if l == nil {
		return nil
	}
	return l.Query
}
