// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// MatchExpr - A single request match expression. Exactly one of `path`, `method`,
// `header` or `queryParam` must be set.
type MatchExpr struct {
	// Matches on the request path.
	Path *PathMatch `json:"path,omitempty"`
	// Matches when the request method is one of the listed methods.
	Method *MethodMatch `json:"method,omitempty"`
	// Matches a named request field (header or query parameter). Exactly one of
	// `present` or `value` must be set.
	Header *FieldMatch `json:"header,omitempty"`
	// Matches a named request field (header or query parameter). Exactly one of
	// `present` or `value` must be set.
	QueryParam *FieldMatch `json:"queryParam,omitempty"`
}

func (m *MatchExpr) GetPath() *PathMatch {
	if m == nil {
		return nil
	}
	return m.Path
}

func (m *MatchExpr) GetMethod() *MethodMatch {
	if m == nil {
		return nil
	}
	return m.Method
}

func (m *MatchExpr) GetHeader() *FieldMatch {
	if m == nil {
		return nil
	}
	return m.Header
}

func (m *MatchExpr) GetQueryParam() *FieldMatch {
	if m == nil {
		return nil
	}
	return m.QueryParam
}
