// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/unkeyed/sdks/api/go/v3/internal/utils"
)

// MatchExpr - A single request match expression. Exactly one of `path`, `method`,
// `header`, `queryParam` or `remoteIp` must be set.
type MatchExpr struct {
	// Matches on the request path.
	Path *PathMatch `json:"path,omitzero"`
	// Matches when the request method is one of the listed methods.
	Method *MethodMatch `json:"method,omitzero"`
	// Matches a named request field (header or query parameter). Exactly one of
	// `present` or `value` must be set.
	Header *FieldMatch `json:"header,omitzero"`
	// Matches a named request field (header or query parameter). Exactly one of
	// `present` or `value` must be set.
	QueryParam *FieldMatch `json:"queryParam,omitzero"`
	// Matches the remote IP against IPv4 or IPv6 CIDR ranges. Exactly one of `in`
	// or `notIn` must be set. Entries are rejected if they have host bits set (such
	// as `10.1.2.3/8`), are IPv4-mapped IPv6 addresses, or carry a zone. Single
	// addresses are returned as full-length prefixes, such as `203.0.113.7/32`.
	RemoteIP *RemoteIPMatch `json:"remoteIp,omitzero"`
}

func (m MatchExpr) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(m, "", false)
}

func (m *MatchExpr) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &m, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (m *MatchExpr) GetPath() *PathMatch {
	if m == nil {
		return nil
	}
	return m.Path
}

func (m *MatchExpr) GetMethod() *MethodMatch {
	if m == nil {
		return nil
	}
	return m.Method
}

func (m *MatchExpr) GetHeader() *FieldMatch {
	if m == nil {
		return nil
	}
	return m.Header
}

func (m *MatchExpr) GetQueryParam() *FieldMatch {
	if m == nil {
		return nil
	}
	return m.QueryParam
}

func (m *MatchExpr) GetRemoteIP() *RemoteIPMatch {
	if m == nil {
		return nil
	}
	return m.RemoteIP
}
