// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Ratelimit struct {
	// The name of this limit. You will need to use this again when verifying a key.
	Name string `json:"name"`
	// How many requests may pass within a given window before requests are rejected.
	Limit int64 `json:"limit"`
	// The duration for each ratelimit window in milliseconds.
	Duration int64 `json:"duration"`
}

func (o *Ratelimit) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *Ratelimit) GetLimit() int64 {
	if o == nil {
		return 0
	}
	return o.Limit
}

func (o *Ratelimit) GetDuration() int64 {
	if o == nil {
		return 0
	}
	return o.Duration
}
