// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Security struct {
	RootKey *string `security:"scheme,type=http,subtype=bearer,name=Authorization,env=unkey_root_key"`
}

func (s *Security) GetRootKey() *string {
	if s == nil {
		return nil
	}
	return s.RootKey
}
