// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V2ApisGetAPIResponseData struct {
	// The unique identifier of this API within Unkey's system.
	// Used in all operations related to this API including key creation, verification, and management.
	// Always begins with 'api_' followed by alphanumeric characters and underscores.
	// This identifier is permanent and never changes after API creation.
	//
	ID string `json:"id"`
	// The internal name of this API as specified during creation.
	// Used for organization and identification within your workspace.
	// Helps distinguish between different environments, services, or access tiers.
	// Not visible to end users - this is purely for administrative purposes.
	//
	Name string `json:"name"`
}

func (v *V2ApisGetAPIResponseData) GetID() string {
	if v == nil {
		return ""
	}
	return v.ID
}

func (v *V2ApisGetAPIResponseData) GetName() string {
	if v == nil {
		return ""
	}
	return v.Name
}
