// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/unkeyed/sdks/api/go/v2/internal/utils"
)

type V2AppsUpdateAppRequestBody struct {
	// Identifies a resource by either its unique ID or its slug.
	// Accepts a prefixed ID (such as 'proj_' or 'app_') or a slug.
	//
	Project string `json:"project"`
	// Identifies a resource by either its unique ID or its slug.
	// Accepts a prefixed ID (such as 'proj_' or 'app_') or a slug.
	//
	App string `json:"app"`
	// New human-readable name for the app.
	// Omit this field to leave the current name unchanged.
	//
	Name *string `json:"name,omitzero"`
	// Identifies a resource by either its unique ID or its slug.
	// Accepts a prefixed ID (such as 'proj_' or 'app_') or a slug.
	//
	Slug *string `json:"slug,omitzero"`
	// Connect, reconfigure, or disconnect this app's GitHub repository.
	// Omit to leave unchanged, set null to disconnect, or set an object with a
	// "repository" to connect or replace it and/or a "defaultBranch" to set which
	// branch it tracks. Fields are independent, so send only the one you change.
	//
	Git *AppGitUpdateInput `json:"git,omitzero"`
	// Enable or disable delete protection for the app.
	// Omit this field to leave the current setting unchanged.
	//
	DeleteProtection *bool `json:"deleteProtection,omitzero"`
}

func (v V2AppsUpdateAppRequestBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V2AppsUpdateAppRequestBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (v *V2AppsUpdateAppRequestBody) GetProject() string {
	if v == nil {
		return ""
	}
	return v.Project
}

func (v *V2AppsUpdateAppRequestBody) GetApp() string {
	if v == nil {
		return ""
	}
	return v.App
}

func (v *V2AppsUpdateAppRequestBody) GetName() *string {
	if v == nil {
		return nil
	}
	return v.Name
}

func (v *V2AppsUpdateAppRequestBody) GetSlug() *string {
	if v == nil {
		return nil
	}
	return v.Slug
}

func (v *V2AppsUpdateAppRequestBody) GetGit() *AppGitUpdateInput {
	if v == nil {
		return nil
	}
	return v.Git
}

func (v *V2AppsUpdateAppRequestBody) GetDeleteProtection() *bool {
	if v == nil {
		return nil
	}
	return v.DeleteProtection
}

// #region class-body-v2appsupdateapprequestbody
// #endregion class-body-v2appsupdateapprequestbody
