// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V2ApisCreateAPIRequestBody struct {
	// Unique identifier for this API namespace within your workspace.
	// Use descriptive names like 'payment-service-prod' or 'user-api-dev' to clearly identify purpose and environment.
	//
	Name string `json:"name"`
}

func (v *V2ApisCreateAPIRequestBody) GetName() string {
	if v == nil {
		return ""
	}
	return v.Name
}
