// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// V2DeploymentsPromoteDeploymentRequestBody - Promote a ready deployment to become the current deployment for its environment.
type V2DeploymentsPromoteDeploymentRequestBody struct {
	// Identifies a resource by either its unique ID or its slug.
	// Accepts a prefixed ID (such as 'proj_' or 'app_') or a slug.
	//
	DeploymentID string `json:"deploymentId"`
}

func (v *V2DeploymentsPromoteDeploymentRequestBody) GetDeploymentID() string {
	if v == nil {
		return ""
	}
	return v.DeploymentID
}

// #region class-body-v2deploymentspromotedeploymentrequestbody
// #endregion class-body-v2deploymentspromotedeploymentrequestbody
