// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V2DeploymentsListDeploymentsResponseBody struct {
	// Metadata object included in every API response. This provides context about the request and is essential for debugging, audit trails, and support inquiries. The `requestId` is particularly important when troubleshooting issues with the Unkey support team.
	Meta Meta `json:"meta"`
	// Array of deployments, ordered newest first.
	Data []Deployment `json:"data"`
	// Pagination metadata for list endpoints. Provides information necessary to traverse through large result sets efficiently using cursor-based pagination.
	Pagination Pagination `json:"pagination"`
}

func (v *V2DeploymentsListDeploymentsResponseBody) GetMeta() Meta {
	if v == nil {
		return Meta{}
	}
	return v.Meta
}

func (v *V2DeploymentsListDeploymentsResponseBody) GetData() []Deployment {
	if v == nil {
		return []Deployment{}
	}
	return v.Data
}

func (v *V2DeploymentsListDeploymentsResponseBody) GetPagination() Pagination {
	if v == nil {
		return Pagination{}
	}
	return v.Pagination
}

// #region class-body-v2deploymentslistdeploymentsresponsebody
// #endregion class-body-v2deploymentslistdeploymentsresponsebody
