// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// V2DeployGitCommit - Optional git commit information
type V2DeployGitCommit struct {
	// Git commit SHA
	CommitSha *string `json:"commitSha,omitzero"`
	// Git commit message
	CommitMessage *string `json:"commitMessage,omitzero"`
	// Git author handle/username
	AuthorHandle *string `json:"authorHandle,omitzero"`
	// Git author avatar URL
	AuthorAvatarURL *string `json:"authorAvatarUrl,omitzero"`
	// Commit timestamp in milliseconds
	Timestamp *int64 `json:"timestamp,omitzero"`
}

func (v *V2DeployGitCommit) GetCommitSha() *string {
	if v == nil {
		return nil
	}
	return v.CommitSha
}

func (v *V2DeployGitCommit) GetCommitMessage() *string {
	if v == nil {
		return nil
	}
	return v.CommitMessage
}

func (v *V2DeployGitCommit) GetAuthorHandle() *string {
	if v == nil {
		return nil
	}
	return v.AuthorHandle
}

func (v *V2DeployGitCommit) GetAuthorAvatarURL() *string {
	if v == nil {
		return nil
	}
	return v.AuthorAvatarURL
}

func (v *V2DeployGitCommit) GetTimestamp() *int64 {
	if v == nil {
		return nil
	}
	return v.Timestamp
}

// #region class-body-v2deploygitcommit
// #endregion class-body-v2deploygitcommit
