// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"errors"
	"fmt"
	"github.com/unkeyed/sdks/api/go/v2/internal/utils"
)

type V2DeploymentsCreateDeploymentRequestBody3 struct {
	// Identifies a resource by either its unique ID or its slug.
	// Accepts a prefixed ID (such as 'proj_' or 'app_') or a slug.
	//
	Project string `json:"project"`
	// Identifies a resource by either its unique ID or its slug.
	// Accepts a prefixed ID (such as 'proj_' or 'app_') or a slug.
	//
	App string `json:"app"`
	// Identifies a resource by either its unique ID or its slug.
	// Accepts a prefixed ID (such as 'proj_' or 'app_') or a slug.
	//
	Environment string `json:"environment"`
	// Build from the app's connected GitHub repository.
	Git *DeploymentSourceGit `json:"git,omitempty"`
	// Deploy a prebuilt Docker image as-is.
	Image *DeploymentSourceImage `json:"image,omitempty"`
	// Re-run an existing deployment.
	Deployment DeploymentSourceDeployment `json:"deployment"`
}

func (v V2DeploymentsCreateDeploymentRequestBody3) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V2DeploymentsCreateDeploymentRequestBody3) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, []string{"project", "app", "environment", "deployment"}); err != nil {
		return err
	}
	return nil
}

func (v *V2DeploymentsCreateDeploymentRequestBody3) GetProject() string {
	if v == nil {
		return ""
	}
	return v.Project
}

func (v *V2DeploymentsCreateDeploymentRequestBody3) GetApp() string {
	if v == nil {
		return ""
	}
	return v.App
}

func (v *V2DeploymentsCreateDeploymentRequestBody3) GetEnvironment() string {
	if v == nil {
		return ""
	}
	return v.Environment
}

func (v *V2DeploymentsCreateDeploymentRequestBody3) GetGit() *DeploymentSourceGit {
	if v == nil {
		return nil
	}
	return v.Git
}

func (v *V2DeploymentsCreateDeploymentRequestBody3) GetImage() *DeploymentSourceImage {
	if v == nil {
		return nil
	}
	return v.Image
}

func (v *V2DeploymentsCreateDeploymentRequestBody3) GetDeployment() DeploymentSourceDeployment {
	if v == nil {
		return DeploymentSourceDeployment{}
	}
	return v.Deployment
}

// #region class-body-v2deploymentscreatedeploymentrequestbody3
// #endregion class-body-v2deploymentscreatedeploymentrequestbody3

type V2DeploymentsCreateDeploymentRequestBody2 struct {
	// Identifies a resource by either its unique ID or its slug.
	// Accepts a prefixed ID (such as 'proj_' or 'app_') or a slug.
	//
	Project string `json:"project"`
	// Identifies a resource by either its unique ID or its slug.
	// Accepts a prefixed ID (such as 'proj_' or 'app_') or a slug.
	//
	App string `json:"app"`
	// Identifies a resource by either its unique ID or its slug.
	// Accepts a prefixed ID (such as 'proj_' or 'app_') or a slug.
	//
	Environment string `json:"environment"`
	// Build from the app's connected GitHub repository.
	Git DeploymentSourceGit `json:"git"`
	// Deploy a prebuilt Docker image as-is.
	Image *DeploymentSourceImage `json:"image,omitempty"`
	// Re-run an existing deployment.
	Deployment *DeploymentSourceDeployment `json:"deployment,omitempty"`
}

func (v V2DeploymentsCreateDeploymentRequestBody2) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V2DeploymentsCreateDeploymentRequestBody2) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, []string{"project", "app", "environment", "git"}); err != nil {
		return err
	}
	return nil
}

func (v *V2DeploymentsCreateDeploymentRequestBody2) GetProject() string {
	if v == nil {
		return ""
	}
	return v.Project
}

func (v *V2DeploymentsCreateDeploymentRequestBody2) GetApp() string {
	if v == nil {
		return ""
	}
	return v.App
}

func (v *V2DeploymentsCreateDeploymentRequestBody2) GetEnvironment() string {
	if v == nil {
		return ""
	}
	return v.Environment
}

func (v *V2DeploymentsCreateDeploymentRequestBody2) GetGit() DeploymentSourceGit {
	if v == nil {
		return DeploymentSourceGit{}
	}
	return v.Git
}

func (v *V2DeploymentsCreateDeploymentRequestBody2) GetImage() *DeploymentSourceImage {
	if v == nil {
		return nil
	}
	return v.Image
}

func (v *V2DeploymentsCreateDeploymentRequestBody2) GetDeployment() *DeploymentSourceDeployment {
	if v == nil {
		return nil
	}
	return v.Deployment
}

// #region class-body-v2deploymentscreatedeploymentrequestbody2
// #endregion class-body-v2deploymentscreatedeploymentrequestbody2

type V2DeploymentsCreateDeploymentRequestBody1 struct {
	// Identifies a resource by either its unique ID or its slug.
	// Accepts a prefixed ID (such as 'proj_' or 'app_') or a slug.
	//
	Project string `json:"project"`
	// Identifies a resource by either its unique ID or its slug.
	// Accepts a prefixed ID (such as 'proj_' or 'app_') or a slug.
	//
	App string `json:"app"`
	// Identifies a resource by either its unique ID or its slug.
	// Accepts a prefixed ID (such as 'proj_' or 'app_') or a slug.
	//
	Environment string `json:"environment"`
	// Build from the app's connected GitHub repository.
	Git *DeploymentSourceGit `json:"git,omitempty"`
	// Deploy a prebuilt Docker image as-is.
	Image DeploymentSourceImage `json:"image"`
	// Re-run an existing deployment.
	Deployment *DeploymentSourceDeployment `json:"deployment,omitempty"`
}

func (v V2DeploymentsCreateDeploymentRequestBody1) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V2DeploymentsCreateDeploymentRequestBody1) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, []string{"project", "app", "environment", "image"}); err != nil {
		return err
	}
	return nil
}

func (v *V2DeploymentsCreateDeploymentRequestBody1) GetProject() string {
	if v == nil {
		return ""
	}
	return v.Project
}

func (v *V2DeploymentsCreateDeploymentRequestBody1) GetApp() string {
	if v == nil {
		return ""
	}
	return v.App
}

func (v *V2DeploymentsCreateDeploymentRequestBody1) GetEnvironment() string {
	if v == nil {
		return ""
	}
	return v.Environment
}

func (v *V2DeploymentsCreateDeploymentRequestBody1) GetGit() *DeploymentSourceGit {
	if v == nil {
		return nil
	}
	return v.Git
}

func (v *V2DeploymentsCreateDeploymentRequestBody1) GetImage() DeploymentSourceImage {
	if v == nil {
		return DeploymentSourceImage{}
	}
	return v.Image
}

func (v *V2DeploymentsCreateDeploymentRequestBody1) GetDeployment() *DeploymentSourceDeployment {
	if v == nil {
		return nil
	}
	return v.Deployment
}

// #region class-body-v2deploymentscreatedeploymentrequestbody1
// #endregion class-body-v2deploymentscreatedeploymentrequestbody1

type V2DeploymentsCreateDeploymentRequestBodyUnionType string

const (
	V2DeploymentsCreateDeploymentRequestBodyUnionTypeV2DeploymentsCreateDeploymentRequestBody1 V2DeploymentsCreateDeploymentRequestBodyUnionType = "V2DeploymentsCreateDeploymentRequestBody_1"
	V2DeploymentsCreateDeploymentRequestBodyUnionTypeV2DeploymentsCreateDeploymentRequestBody2 V2DeploymentsCreateDeploymentRequestBodyUnionType = "V2DeploymentsCreateDeploymentRequestBody_2"
	V2DeploymentsCreateDeploymentRequestBodyUnionTypeV2DeploymentsCreateDeploymentRequestBody3 V2DeploymentsCreateDeploymentRequestBodyUnionType = "V2DeploymentsCreateDeploymentRequestBody_3"
)

// V2DeploymentsCreateDeploymentRequestBodyUnion - Create a deployment. Provide exactly one of git, image, or deployment.
type V2DeploymentsCreateDeploymentRequestBodyUnion struct {
	V2DeploymentsCreateDeploymentRequestBody1 *V2DeploymentsCreateDeploymentRequestBody1 `queryParam:"inline" union:"member"`
	V2DeploymentsCreateDeploymentRequestBody2 *V2DeploymentsCreateDeploymentRequestBody2 `queryParam:"inline" union:"member"`
	V2DeploymentsCreateDeploymentRequestBody3 *V2DeploymentsCreateDeploymentRequestBody3 `queryParam:"inline" union:"member"`

	Type V2DeploymentsCreateDeploymentRequestBodyUnionType
}

func CreateV2DeploymentsCreateDeploymentRequestBodyUnionV2DeploymentsCreateDeploymentRequestBody1(v2DeploymentsCreateDeploymentRequestBody1 V2DeploymentsCreateDeploymentRequestBody1) V2DeploymentsCreateDeploymentRequestBodyUnion {
	typ := V2DeploymentsCreateDeploymentRequestBodyUnionTypeV2DeploymentsCreateDeploymentRequestBody1

	return V2DeploymentsCreateDeploymentRequestBodyUnion{
		V2DeploymentsCreateDeploymentRequestBody1: &v2DeploymentsCreateDeploymentRequestBody1,
		Type: typ,
	}
}

func CreateV2DeploymentsCreateDeploymentRequestBodyUnionV2DeploymentsCreateDeploymentRequestBody2(v2DeploymentsCreateDeploymentRequestBody2 V2DeploymentsCreateDeploymentRequestBody2) V2DeploymentsCreateDeploymentRequestBodyUnion {
	typ := V2DeploymentsCreateDeploymentRequestBodyUnionTypeV2DeploymentsCreateDeploymentRequestBody2

	return V2DeploymentsCreateDeploymentRequestBodyUnion{
		V2DeploymentsCreateDeploymentRequestBody2: &v2DeploymentsCreateDeploymentRequestBody2,
		Type: typ,
	}
}

func CreateV2DeploymentsCreateDeploymentRequestBodyUnionV2DeploymentsCreateDeploymentRequestBody3(v2DeploymentsCreateDeploymentRequestBody3 V2DeploymentsCreateDeploymentRequestBody3) V2DeploymentsCreateDeploymentRequestBodyUnion {
	typ := V2DeploymentsCreateDeploymentRequestBodyUnionTypeV2DeploymentsCreateDeploymentRequestBody3

	return V2DeploymentsCreateDeploymentRequestBodyUnion{
		V2DeploymentsCreateDeploymentRequestBody3: &v2DeploymentsCreateDeploymentRequestBody3,
		Type: typ,
	}
}

func (u *V2DeploymentsCreateDeploymentRequestBodyUnion) UnmarshalJSON(data []byte) error {

	var v2DeploymentsCreateDeploymentRequestBody1 V2DeploymentsCreateDeploymentRequestBody1 = V2DeploymentsCreateDeploymentRequestBody1{}
	if err := utils.UnmarshalJSON(data, &v2DeploymentsCreateDeploymentRequestBody1, "", true, nil); err == nil {
		u.V2DeploymentsCreateDeploymentRequestBody1 = &v2DeploymentsCreateDeploymentRequestBody1
		u.Type = V2DeploymentsCreateDeploymentRequestBodyUnionTypeV2DeploymentsCreateDeploymentRequestBody1
		return nil
	}

	var v2DeploymentsCreateDeploymentRequestBody2 V2DeploymentsCreateDeploymentRequestBody2 = V2DeploymentsCreateDeploymentRequestBody2{}
	if err := utils.UnmarshalJSON(data, &v2DeploymentsCreateDeploymentRequestBody2, "", true, nil); err == nil {
		u.V2DeploymentsCreateDeploymentRequestBody2 = &v2DeploymentsCreateDeploymentRequestBody2
		u.Type = V2DeploymentsCreateDeploymentRequestBodyUnionTypeV2DeploymentsCreateDeploymentRequestBody2
		return nil
	}

	var v2DeploymentsCreateDeploymentRequestBody3 V2DeploymentsCreateDeploymentRequestBody3 = V2DeploymentsCreateDeploymentRequestBody3{}
	if err := utils.UnmarshalJSON(data, &v2DeploymentsCreateDeploymentRequestBody3, "", true, nil); err == nil {
		u.V2DeploymentsCreateDeploymentRequestBody3 = &v2DeploymentsCreateDeploymentRequestBody3
		u.Type = V2DeploymentsCreateDeploymentRequestBodyUnionTypeV2DeploymentsCreateDeploymentRequestBody3
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for V2DeploymentsCreateDeploymentRequestBodyUnion", string(data))
}

func (u V2DeploymentsCreateDeploymentRequestBodyUnion) MarshalJSON() ([]byte, error) {
	if u.V2DeploymentsCreateDeploymentRequestBody1 != nil {
		return utils.MarshalJSON(u.V2DeploymentsCreateDeploymentRequestBody1, "", true)
	}

	if u.V2DeploymentsCreateDeploymentRequestBody2 != nil {
		return utils.MarshalJSON(u.V2DeploymentsCreateDeploymentRequestBody2, "", true)
	}

	if u.V2DeploymentsCreateDeploymentRequestBody3 != nil {
		return utils.MarshalJSON(u.V2DeploymentsCreateDeploymentRequestBody3, "", true)
	}

	return nil, errors.New("could not marshal union type V2DeploymentsCreateDeploymentRequestBodyUnion: all fields are null")
}
