// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V2DeployGenerateUploadURLRequestBody struct {
	// Unkey project ID for which to generate the upload URL
	ProjectID string `json:"projectId"`
}

func (v *V2DeployGenerateUploadURLRequestBody) GetProjectID() string {
	if v == nil {
		return ""
	}
	return v.ProjectID
}
