// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/unkeyed/sdks/api/go/v2/internal/utils"
)

type V2EnvironmentsSetEnvironmentVariablesRequestBody struct {
	// Identifies a resource by either its unique ID or its slug.
	// Accepts a prefixed ID (such as 'proj_' or 'app_') or a slug.
	//
	Project string `json:"project"`
	// Identifies a resource by either its unique ID or its slug.
	// Accepts a prefixed ID (such as 'proj_' or 'app_') or a slug.
	//
	App string `json:"app"`
	// Identifies a resource by either its unique ID or its slug.
	// Accepts a prefixed ID (such as 'proj_' or 'app_') or a slug.
	//
	Environment string `json:"environment"`
	// The variables to upsert. Each entry is created if its key is new or fully
	// overwritten if the key already exists. Existing variables whose keys are
	// not in this list are left untouched, unless `prune` is true.
	//
	// Each entry is written exactly as sent, never merged with the current
	// state. Only `value` is required; omitted optional fields (`kind`,
	// `description`) fall back to their defaults rather than any previous value,
	// so overwriting a variable without a `description` clears it.
	//
	// Each key may appear at most once; a duplicate key is rejected with a 400.
	// The whole operation is atomic: if any part fails the environment is left
	// unchanged. All values are encrypted at rest. Limited to 50 variables per
	// request.
	//
	Variables []EnvironmentVariableInput `json:"variables"`
	// Optional. Defaults to false. When false, the variables above are upserted
	// and any existing variable not in the list is kept. When true, this becomes
	// a full replace: after upserting, every variable not in the list is deleted.
	// Combined with an empty `variables` list, `prune: true` resets the entire
	// environment by deleting every variable.
	Prune *bool `default:"false" json:"prune"`
}

func (v V2EnvironmentsSetEnvironmentVariablesRequestBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V2EnvironmentsSetEnvironmentVariablesRequestBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (v *V2EnvironmentsSetEnvironmentVariablesRequestBody) GetProject() string {
	if v == nil {
		return ""
	}
	return v.Project
}

func (v *V2EnvironmentsSetEnvironmentVariablesRequestBody) GetApp() string {
	if v == nil {
		return ""
	}
	return v.App
}

func (v *V2EnvironmentsSetEnvironmentVariablesRequestBody) GetEnvironment() string {
	if v == nil {
		return ""
	}
	return v.Environment
}

func (v *V2EnvironmentsSetEnvironmentVariablesRequestBody) GetVariables() []EnvironmentVariableInput {
	if v == nil {
		return []EnvironmentVariableInput{}
	}
	return v.Variables
}

func (v *V2EnvironmentsSetEnvironmentVariablesRequestBody) GetPrune() *bool {
	if v == nil {
		return nil
	}
	return v.Prune
}

// #region class-body-v2environmentssetenvironmentvariablesrequestbody
// #endregion class-body-v2environmentssetenvironmentvariablesrequestbody
