// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V2EnvironmentsRemoveEnvironmentVariablesRequestBody struct {
	// Identifies a resource by either its unique ID or its slug.
	// Accepts a prefixed ID (such as 'proj_' or 'app_') or a slug.
	//
	Project string `json:"project"`
	// Identifies a resource by either its unique ID or its slug.
	// Accepts a prefixed ID (such as 'proj_' or 'app_') or a slug.
	//
	App string `json:"app"`
	// Identifies a resource by either its unique ID or its slug.
	// Accepts a prefixed ID (such as 'proj_' or 'app_') or a slug.
	//
	Environment string `json:"environment"`
	// The names of the variables to remove. Keys that exist are deleted; keys
	// that are not present are ignored, since their absence already matches the
	// requested state.
	//
	// Duplicate keys collapse to a single removal. The whole operation is atomic:
	// if any part fails the environment is left unchanged. Limited to 50
	// variables per request.
	//
	Variables []string `json:"variables"`
}

func (v *V2EnvironmentsRemoveEnvironmentVariablesRequestBody) GetProject() string {
	if v == nil {
		return ""
	}
	return v.Project
}

func (v *V2EnvironmentsRemoveEnvironmentVariablesRequestBody) GetApp() string {
	if v == nil {
		return ""
	}
	return v.App
}

func (v *V2EnvironmentsRemoveEnvironmentVariablesRequestBody) GetEnvironment() string {
	if v == nil {
		return ""
	}
	return v.Environment
}

func (v *V2EnvironmentsRemoveEnvironmentVariablesRequestBody) GetVariables() []string {
	if v == nil {
		return []string{}
	}
	return v.Variables
}

// #region class-body-v2environmentsremoveenvironmentvariablesrequestbody
// #endregion class-body-v2environmentsremoveenvironmentvariablesrequestbody
