// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// V2IdentitiesCreateIdentityRequestBodyMeta - Attach metadata to this identity that you need to have access to when verifying a key.
//
// This will be returned as part of the `verifyKey` response.
type V2IdentitiesCreateIdentityRequestBodyMeta struct {
}

type V2IdentitiesCreateIdentityRequestBody struct {
	// The id of this identity in your system.
	//
	// This usually comes from your authentication provider and could be a userId, organisationId or even an email.
	// It does not matter what you use, as long as it uniquely identifies something in your application.
	//
	// `externalId`s are unique across your workspace and therefore a `CONFLICT` error is returned when you try to create duplicates.
	//
	ExternalID string `json:"externalId"`
	// Attach metadata to this identity that you need to have access to when verifying a key.
	//
	// This will be returned as part of the `verifyKey` response.
	//
	Meta *V2IdentitiesCreateIdentityRequestBodyMeta `json:"meta,omitempty"`
	// Attach ratelimits to this identity.
	//
	// When verifying keys, you can specify which limits you want to use and all keys attached to this identity, will share the limits.
	Ratelimits []Ratelimit `json:"ratelimits,omitempty"`
}

func (o *V2IdentitiesCreateIdentityRequestBody) GetExternalID() string {
	if o == nil {
		return ""
	}
	return o.ExternalID
}

func (o *V2IdentitiesCreateIdentityRequestBody) GetMeta() *V2IdentitiesCreateIdentityRequestBodyMeta {
	if o == nil {
		return nil
	}
	return o.Meta
}

func (o *V2IdentitiesCreateIdentityRequestBody) GetRatelimits() []Ratelimit {
	if o == nil {
		return nil
	}
	return o.Ratelimits
}
