// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V2IdentitiesCreateIdentityResponseBody struct {
	Meta Meta                                 `json:"meta"`
	Data IdentitiesCreateIdentityResponseData `json:"data"`
}

func (o *V2IdentitiesCreateIdentityResponseBody) GetMeta() Meta {
	if o == nil {
		return Meta{}
	}
	return o.Meta
}

func (o *V2IdentitiesCreateIdentityResponseBody) GetData() IdentitiesCreateIdentityResponseData {
	if o == nil {
		return IdentitiesCreateIdentityResponseData{}
	}
	return o.Data
}
