// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V2KeysRemovePermissionsRequestBody struct {
	// Specifies which key to remove permissions from using the database identifier returned from `keys.createKey`.
	// Do not confuse this with the actual API key string that users include in requests.
	//
	KeyID string `json:"keyId"`
	// Removes direct permissions from the key without affecting role-based permissions.
	//
	// You can either use a permission slug, or the permission ID.
	//
	// After removal, verification checks for these permissions will fail unless granted through roles.
	//
	Permissions []string `json:"permissions"`
}

func (o *V2KeysRemovePermissionsRequestBody) GetKeyID() string {
	if o == nil {
		return ""
	}
	return o.KeyID
}

func (o *V2KeysRemovePermissionsRequestBody) GetPermissions() []string {
	if o == nil {
		return []string{}
	}
	return o.Permissions
}
