// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V2KeysMigrateKeysMigration struct {
	// The hash provided in the migration request
	Hash string `json:"hash"`
	// The unique identifier for this key in Unkey's system. This is NOT the actual API key, but a reference ID used for management operations like updating or deleting the key. Store this ID in your database to reference the key later. This ID is not sensitive and can be logged or displayed in dashboards.
	KeyID string `json:"keyId"`
}

func (v *V2KeysMigrateKeysMigration) GetHash() string {
	if v == nil {
		return ""
	}
	return v.Hash
}

func (v *V2KeysMigrateKeysMigration) GetKeyID() string {
	if v == nil {
		return ""
	}
	return v.KeyID
}
