// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V2KeysRemovePermissionsResponseBody struct {
	// Metadata object included in every API response. This provides context about the request and is essential for debugging, audit trails, and support inquiries. The `requestId` is particularly important when troubleshooting issues with the Unkey support team.
	Meta Meta `json:"meta"`
	// Complete list of all permissions directly assigned to the key after the removal operation (remaining permissions only).
	//
	// Notes:
	// - This list does NOT include permissions granted through roles
	// - For a complete permission picture, use `/v2/keys.getKey` instead
	// - An empty array indicates the key has no direct permissions assigned
	// - Any cached versions of the key are immediately invalidated to ensure consistency
	// - Changes to permissions take effect within seconds for new verifications
	Data []Permission `json:"data"`
}

func (o *V2KeysRemovePermissionsResponseBody) GetMeta() Meta {
	if o == nil {
		return Meta{}
	}
	return o.Meta
}

func (o *V2KeysRemovePermissionsResponseBody) GetData() []Permission {
	if o == nil {
		return []Permission{}
	}
	return o.Data
}
