// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V2KeysRerollKeyResponseBody struct {
	// Metadata object included in every API response. This provides context about the request and is essential for debugging, audit trails, and support inquiries. The `requestId` is particularly important when troubleshooting issues with the Unkey support team.
	Meta Meta                        `json:"meta"`
	Data V2KeysRerollKeyResponseData `json:"data"`
}

func (o *V2KeysRerollKeyResponseBody) GetMeta() Meta {
	if o == nil {
		return Meta{}
	}
	return o.Meta
}

func (o *V2KeysRerollKeyResponseBody) GetData() V2KeysRerollKeyResponseData {
	if o == nil {
		return V2KeysRerollKeyResponseData{}
	}
	return o.Data
}
