// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V2KeysCreateKeyResponseBody struct {
	// Metadata object included in every API response. This provides context about the request and is essential for debugging, audit trails, and support inquiries. The `requestId` is particularly important when troubleshooting issues with the Unkey support team.
	Meta Meta                        `json:"meta"`
	Data V2KeysCreateKeyResponseData `json:"data"`
}

func (v *V2KeysCreateKeyResponseBody) GetMeta() Meta {
	if v == nil {
		return Meta{}
	}
	return v.Meta
}

func (v *V2KeysCreateKeyResponseBody) GetData() V2KeysCreateKeyResponseData {
	if v == nil {
		return V2KeysCreateKeyResponseData{}
	}
	return v.Data
}
