// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/unkeyed/sdks/api/go/v3/optionalnullable"
)

type V2PermissionsUpdatePermissionRequestBody struct {
	// The permission to update. Pass the permission ID (`perm_...`) or its current slug.
	//
	Permission string `json:"permission"`
	// New human-readable name for the permission.
	// Omit this field to keep the current name.
	//
	Name *string `json:"name,omitzero"`
	// New slug for the permission. Keys and roles that have this permission get the new slug in verification responses.
	// The slug must be unique in your workspace.
	// Omit this field to keep the current slug.
	//
	Slug *string `json:"slug,omitzero"`
	// New description for the permission.
	// Omit this field to keep the current description. Send null or an empty string to remove it.
	//
	Description optionalnullable.OptionalNullable[string] `json:"description,omitzero"`
}

func (v *V2PermissionsUpdatePermissionRequestBody) GetPermission() string {
	if v == nil {
		return ""
	}
	return v.Permission
}

func (v *V2PermissionsUpdatePermissionRequestBody) GetName() *string {
	if v == nil {
		return nil
	}
	return v.Name
}

func (v *V2PermissionsUpdatePermissionRequestBody) GetSlug() *string {
	if v == nil {
		return nil
	}
	return v.Slug
}

func (v *V2PermissionsUpdatePermissionRequestBody) GetDescription() optionalnullable.OptionalNullable[string] {
	if v == nil {
		return nil
	}
	return v.Description
}

// #region class-body-v2permissionsupdatepermissionrequestbody
// #endregion class-body-v2permissionsupdatepermissionrequestbody
