// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V2PermissionsGetRoleRequestBody struct {
	// Unique identifier of the role to permanently delete from your workspace.
	// Must either be a valid role ID that begins with 'role_' or the given role name and exists within your workspace.
	//
	// Use this endpoint to verify role details, check its current permissions, or retrieve metadata.
	// Returns complete role information including all assigned permissions for comprehensive access review.
	//
	Role string `json:"role"`
}

func (v *V2PermissionsGetRoleRequestBody) GetRole() string {
	if v == nil {
		return ""
	}
	return v.Role
}
