// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V2PermissionsCreatePermissionResponseData struct {
	// The unique identifier assigned to the newly created permission.
	// Use this ID to reference the permission in role assignments, key operations, and other API calls.
	// Always begins with 'perm_' followed by a unique alphanumeric sequence.
	// Store this ID if you need to manage or reference this permission in future operations.
	//
	PermissionID string `json:"permissionId"`
}

func (v *V2PermissionsCreatePermissionResponseData) GetPermissionID() string {
	if v == nil {
		return ""
	}
	return v.PermissionID
}
