// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V2PortalCreateSessionResponseData struct {
	// The portal session's identifier. Not a credential: it is safe to log and
	// to store against your own records of the end user's visit.
	//
	ID string `json:"id"`
	// The full portal URL to redirect the end user to. Carries a single-use
	// exchange code that is valid for 15 minutes.
	//
	URL string `json:"url"`
}

func (v *V2PortalCreateSessionResponseData) GetID() string {
	if v == nil {
		return ""
	}
	return v.ID
}

func (v *V2PortalCreateSessionResponseData) GetURL() string {
	if v == nil {
		return ""
	}
	return v.URL
}

// #region class-body-v2portalcreatesessionresponsedata
// #endregion class-body-v2portalcreatesessionresponsedata
