// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V2RatelimitDeleteOverrideResponseBody struct {
	// Metadata object included in every API response. This provides context about the request and is essential for debugging, audit trails, and support inquiries. The `requestId` is particularly important when troubleshooting issues with the Unkey support team.
	Meta Meta `json:"meta"`
	// Empty response object. A successful response indicates the override was successfully deleted. The operation is immediate - as soon as this response is received, the override no longer exists and affected identifiers have reverted to using the default rate limit for the namespace. No other data is returned as part of the deletion operation.
	Data V2RatelimitDeleteOverrideResponseData `json:"data"`
}

func (v *V2RatelimitDeleteOverrideResponseBody) GetMeta() Meta {
	if v == nil {
		return Meta{}
	}
	return v.Meta
}

func (v *V2RatelimitDeleteOverrideResponseBody) GetData() V2RatelimitDeleteOverrideResponseData {
	if v == nil {
		return V2RatelimitDeleteOverrideResponseData{}
	}
	return v.Data
}
