// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V2RatelimitLimitResponseBody struct {
	// Metadata object included in every API response. This provides context about the request and is essential for debugging, audit trails, and support inquiries. The `requestId` is particularly important when troubleshooting issues with the Unkey support team.
	Meta Meta                         `json:"meta"`
	Data V2RatelimitLimitResponseData `json:"data"`
}

func (v *V2RatelimitLimitResponseBody) GetMeta() Meta {
	if v == nil {
		return Meta{}
	}
	return v.Meta
}

func (v *V2RatelimitLimitResponseBody) GetData() V2RatelimitLimitResponseData {
	if v == nil {
		return V2RatelimitLimitResponseData{}
	}
	return v.Data
}
