// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// V2RatelimitSetOverrideRequestBody - Sets a new or overwrites an existing override.
type V2RatelimitSetOverrideRequestBody struct {
	// The id of the namespace. Either namespaceId or namespaceName must be provided
	NamespaceID *string `json:"namespaceId,omitempty"`
	// The name of the namespace. Either namespaceId or namespaceName must be provided
	NamespaceName *string `json:"namespaceName,omitempty"`
	// The duration in milliseconds for the rate limit window.
	Duration int64 `json:"duration"`
	// Identifier of your user, this can be their userId, an email, an ip or anything else. Wildcards ( * ) can be used to match multiple identifiers, More info can be found at https://www.unkey.com/docs/ratelimiting/overrides#wildcard-rules
	Identifier string `json:"identifier"`
	// The maximum number of requests allowed.
	Limit int64 `json:"limit"`
}

func (o *V2RatelimitSetOverrideRequestBody) GetNamespaceID() *string {
	if o == nil {
		return nil
	}
	return o.NamespaceID
}

func (o *V2RatelimitSetOverrideRequestBody) GetNamespaceName() *string {
	if o == nil {
		return nil
	}
	return o.NamespaceName
}

func (o *V2RatelimitSetOverrideRequestBody) GetDuration() int64 {
	if o == nil {
		return 0
	}
	return o.Duration
}

func (o *V2RatelimitSetOverrideRequestBody) GetIdentifier() string {
	if o == nil {
		return ""
	}
	return o.Identifier
}

func (o *V2RatelimitSetOverrideRequestBody) GetLimit() int64 {
	if o == nil {
		return 0
	}
	return o.Limit
}
