// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/unkeyed/sdks/api/go/v3/optionalnullable"
)

type V2RootKeysCreateKeyRequestBody struct {
	// Optional name for the root key.
	Name *string `json:"name,omitzero"`
	// Permissions to grant to the root key. Each permission must be within the caller's existing permissions.
	Permissions []string `json:"permissions"`
	// Expiration as Unix milliseconds, strictly in the future. Expiring root-key callers must provide a child expiry no later than their own. JWT admins and nonexpiring root-key callers may omit it or set null for no expiration.
	Expires optionalnullable.OptionalNullable[int64] `json:"expires,omitzero"`
}

func (v *V2RootKeysCreateKeyRequestBody) GetName() *string {
	if v == nil {
		return nil
	}
	return v.Name
}

func (v *V2RootKeysCreateKeyRequestBody) GetPermissions() []string {
	if v == nil {
		return []string{}
	}
	return v.Permissions
}

func (v *V2RootKeysCreateKeyRequestBody) GetExpires() optionalnullable.OptionalNullable[int64] {
	if v == nil {
		return nil
	}
	return v.Expires
}

// #region class-body-v2rootkeyscreatekeyrequestbody
// #endregion class-body-v2rootkeyscreatekeyrequestbody
