// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/unkeyed/sdks/api/go/v3/internal/utils"
)

// V2WorkspaceGetUsageByAppRow - Active gateway keys counted for one app in the period.
type V2WorkspaceGetUsageByAppRow struct {
	// The project the app belongs to. Omitted when the app was deleted or `app` is omitted.
	Project *V2WorkspaceGetUsageResource `json:"project,omitzero"`
	// The app whose gateway verified the keys. Omitted for keys whose
	// verifications were all recorded before Unkey stored app ids.
	//
	App *V2WorkspaceGetUsageResource `json:"app,omitzero"`
	// Unkey gateway usage in the period.
	Gateway V2WorkspaceGetUsageGateway `json:"gateway"`
}

func (v V2WorkspaceGetUsageByAppRow) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V2WorkspaceGetUsageByAppRow) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (v *V2WorkspaceGetUsageByAppRow) GetProject() *V2WorkspaceGetUsageResource {
	if v == nil {
		return nil
	}
	return v.Project
}

func (v *V2WorkspaceGetUsageByAppRow) GetApp() *V2WorkspaceGetUsageResource {
	if v == nil {
		return nil
	}
	return v.App
}

func (v *V2WorkspaceGetUsageByAppRow) GetGateway() V2WorkspaceGetUsageGateway {
	if v == nil {
		return V2WorkspaceGetUsageGateway{}
	}
	return v.Gateway
}

// #region class-body-v2workspacegetusagebyapprow
// #endregion class-body-v2workspacegetusagebyapprow
