// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// V2WorkspaceGetUsageGateway - Unkey gateway usage in the period.
type V2WorkspaceGetUsageGateway struct {
	// Distinct keys verified through the Unkey gateway. A key verified through
	// several apps counts once, for the app that verified it most.
	//
	ActiveKeys int64 `json:"activeKeys"`
}

func (v *V2WorkspaceGetUsageGateway) GetActiveKeys() int64 {
	if v == nil {
		return 0
	}
	return v.ActiveKeys
}

// #region class-body-v2workspacegetusagegateway
// #endregion class-body-v2workspacegetusagegateway
