// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type VerifyKeyRatelimitData struct {
	// Whether the rate limit was exceeded.
	Exceeded bool `json:"exceeded"`
	// Unique identifier for this rate limit configuration.
	ID string `json:"id"`
	// Human-readable name for this rate limit.
	Name string `json:"name"`
	// Maximum requests allowed within the time window.
	Limit int64 `json:"limit"`
	// Rate limit window duration in milliseconds.
	Duration int64 `json:"duration"`
	// Rate limit reset duration in milliseconds.
	Reset int64 `json:"reset"`
	// Rate limit remaining requests within the time window.
	Remaining int64 `json:"remaining"`
	// Whether this rate limit should be automatically applied when verifying keys.
	// When true, we will automatically apply this limit during verification without it being explicitly listed.
	//
	AutoApply bool `json:"autoApply"`
}

func (o *VerifyKeyRatelimitData) GetExceeded() bool {
	if o == nil {
		return false
	}
	return o.Exceeded
}

func (o *VerifyKeyRatelimitData) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *VerifyKeyRatelimitData) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *VerifyKeyRatelimitData) GetLimit() int64 {
	if o == nil {
		return 0
	}
	return o.Limit
}

func (o *VerifyKeyRatelimitData) GetDuration() int64 {
	if o == nil {
		return 0
	}
	return o.Duration
}

func (o *VerifyKeyRatelimitData) GetReset() int64 {
	if o == nil {
		return 0
	}
	return o.Reset
}

func (o *VerifyKeyRatelimitData) GetRemaining() int64 {
	if o == nil {
		return 0
	}
	return o.Remaining
}

func (o *VerifyKeyRatelimitData) GetAutoApply() bool {
	if o == nil {
		return false
	}
	return o.AutoApply
}
