"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .v2apislistkeysresponsebody import (
    V2ApisListKeysResponseBody,
    V2ApisListKeysResponseBodyTypedDict,
)
from typing import Callable, Optional
from typing_extensions import TypedDict
from unkey.py.types import BaseModel


class ApisListKeysResponseTypedDict(TypedDict):
    result: V2ApisListKeysResponseBodyTypedDict


class ApisListKeysResponse(BaseModel):
    next: Callable[[], Optional[ApisListKeysResponse]]

    result: V2ApisListKeysResponseBody
