"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from typing_extensions import TypedDict
from unkey.py.types import BaseModel


class DeploymentDockerTypedDict(TypedDict):
    image: str
    r"""The Docker image this deployment runs."""


class DeploymentDocker(BaseModel):
    image: str
    r"""The Docker image this deployment runs."""
