"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from typing_extensions import TypedDict
from unkey.py.types import BaseModel


class DeploymentSourceOCITypedDict(TypedDict):
    r"""Deploy a prebuilt OCI image without a build."""

    image: str
    r"""OCI image to deploy. Mutable tags are resolved to immutable digests before rollout."""


class DeploymentSourceOCI(BaseModel):
    r"""Deploy a prebuilt OCI image without a build."""

    image: str
    r"""OCI image to deploy. Mutable tags are resolved to immutable digests before rollout."""
