"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from typing_extensions import Annotated, TypedDict
from unkey.py.types import BaseModel


class DeploymentSourceImageTypedDict(TypedDict):
    r"""Deploy a prebuilt Docker image as-is."""

    docker_image: str
    r"""Deprecated. Use `oci.image` in v3 instead. This field is the full image reference to deploy as-is. Qualify the version with a tag (ghcr.io/acme/api:v1.2.3) or a digest (ghcr.io/acme/api@sha256:...). Without either, the registry serves the latest tag."""


class DeploymentSourceImage(BaseModel):
    r"""Deploy a prebuilt Docker image as-is."""

    docker_image: Annotated[
        str,
        pydantic.Field(
            deprecated="warning: ** DEPRECATED ** - This will be removed in a future release, please migrate away from it as soon as possible.",
            alias="dockerImage",
        ),
    ]
    r"""Deprecated. Use `oci.image` in v3 instead. This field is the full image reference to deploy as-is. Qualify the version with a tag (ghcr.io/acme/api:v1.2.3) or a digest (ghcr.io/acme/api@sha256:...). Without either, the registry serves the latest tag."""


try:
    DeploymentSourceImage.model_rebuild()
except NameError:
    pass
