"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .ratelimitresponse import RatelimitResponse, RatelimitResponseTypedDict
import pydantic
from pydantic import model_serializer
from typing import Any, Dict, List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict
from unkey.py.types import BaseModel, UNSET_SENTINEL


class IdentityTypedDict(TypedDict):
    id: str
    r"""Identity ID"""
    external_id: str
    r"""External identity ID"""
    meta: NotRequired[Dict[str, Any]]
    r"""Identity metadata"""
    ratelimits: NotRequired[List[RatelimitResponseTypedDict]]
    r"""Identity ratelimits"""


class Identity(BaseModel):
    id: str
    r"""Identity ID"""

    external_id: Annotated[str, pydantic.Field(alias="externalId")]
    r"""External identity ID"""

    meta: Optional[Dict[str, Any]] = None
    r"""Identity metadata"""

    ratelimits: Optional[List[RatelimitResponse]] = None
    r"""Identity ratelimits"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["meta", "ratelimits"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    Identity.model_rebuild()
except NameError:
    pass
