"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .firewallpolicy import FirewallPolicy, FirewallPolicyTypedDict
from .keyauthpolicy import KeyauthPolicy, KeyauthPolicyTypedDict
from .matchexpr import MatchExpr, MatchExprTypedDict
from .openapipolicy import OpenapiPolicy, OpenapiPolicyTypedDict
from .ratelimitpolicy import RatelimitPolicy, RatelimitPolicyTypedDict
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict
from unkey.py.types import BaseModel, UNSET_SENTINEL


class PolicyResponseTypedDict(TypedDict):
    r"""A stored gateway policy as returned by list endpoints. Exactly one of
    `keyauth`, `ratelimit`, `firewall` or `openapi` is set.
    """

    id: str
    r"""Server-generated policy id. Regenerated on every `gateway.setPolicies` call, so treat it as stable only until the environment's policies are next replaced."""
    name: str
    r"""Human-readable name shown in the dashboard."""
    enabled: bool
    r"""Disabled policies are stored but skipped during evaluation."""
    match: NotRequired[List[MatchExprTypedDict]]
    r"""Optional request matchers. The policy applies only to requests matching
    all expressions; omitted when the policy applies to every request.
    """
    keyauth: NotRequired[KeyauthPolicyTypedDict]
    r"""Verifies Unkey API keys on matching requests."""
    ratelimit: NotRequired[RatelimitPolicyTypedDict]
    r"""Rate limits matching requests."""
    firewall: NotRequired[FirewallPolicyTypedDict]
    r"""Blocks matching requests."""
    openapi: NotRequired[OpenapiPolicyTypedDict]
    r"""Validates matching requests against the app's uploaded OpenAPI spec. Has no
    configuration of its own. If no spec has been uploaded for the deployment,
    the policy is a no-op and requests pass through unvalidated.
    """


class PolicyResponse(BaseModel):
    r"""A stored gateway policy as returned by list endpoints. Exactly one of
    `keyauth`, `ratelimit`, `firewall` or `openapi` is set.
    """

    id: str
    r"""Server-generated policy id. Regenerated on every `gateway.setPolicies` call, so treat it as stable only until the environment's policies are next replaced."""

    name: str
    r"""Human-readable name shown in the dashboard."""

    enabled: bool
    r"""Disabled policies are stored but skipped during evaluation."""

    match: Optional[List[MatchExpr]] = None
    r"""Optional request matchers. The policy applies only to requests matching
    all expressions; omitted when the policy applies to every request.
    """

    keyauth: Optional[KeyauthPolicy] = None
    r"""Verifies Unkey API keys on matching requests."""

    ratelimit: Optional[RatelimitPolicy] = None
    r"""Rate limits matching requests."""

    firewall: Optional[FirewallPolicy] = None
    r"""Blocks matching requests."""

    openapi: Optional[OpenapiPolicy] = None
    r"""Validates matching requests against the app's uploaded OpenAPI spec. Has no
    configuration of its own. If no spec has been uploaded for the deployment,
    the policy is a no-op and requests pass through unvalidated.
    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["match", "keyauth", "ratelimit", "firewall", "openapi"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
