"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .v2portallistkeysresponsebody import (
    V2PortalListKeysResponseBody,
    V2PortalListKeysResponseBodyTypedDict,
)
from typing import Callable, Optional
from typing_extensions import Annotated, TypedDict
from unkey.py.types import BaseModel
from unkey.py.utils import FieldMetadata, SecurityMetadata


class PortalListKeysSecurityTypedDict(TypedDict):
    portal_session: str


class PortalListKeysSecurity(BaseModel):
    portal_session: Annotated[
        str,
        FieldMetadata(
            security=SecurityMetadata(
                scheme=True,
                scheme_type="apiKey",
                sub_type="cookie",
                field_name="portal_session",
            )
        ),
    ]


class PortalListKeysResponseTypedDict(TypedDict):
    result: V2PortalListKeysResponseBodyTypedDict


class PortalListKeysResponse(BaseModel):
    next: Callable[[], Optional[PortalListKeysResponse]]

    result: V2PortalListKeysResponseBody
