"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .appgitcreateinput import AppGitCreateInput, AppGitCreateInputTypedDict
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict
from unkey.py.types import BaseModel, UNSET_SENTINEL


class V2AppsCreateAppRequestBodyTypedDict(TypedDict):
    project: str
    r"""Identifies a resource by either its unique ID or its slug.
    Accepts a prefixed ID (such as 'proj_' or 'app_') or a slug.

    """
    name: str
    r"""Human-readable name for this app.
    Use a descriptive name like 'Payments API' to identify its purpose.

    """
    slug: str
    r"""Identifies a resource by either its unique ID or its slug.
    Accepts a prefixed ID (such as 'proj_' or 'app_') or a slug.

    """
    git: NotRequired[AppGitCreateInputTypedDict]
    r"""Connect a GitHub repository to the app on creation. Omit to create the app
    without a repository and connect one later with apps.updateApp.

    """


class V2AppsCreateAppRequestBody(BaseModel):
    project: str
    r"""Identifies a resource by either its unique ID or its slug.
    Accepts a prefixed ID (such as 'proj_' or 'app_') or a slug.

    """

    name: str
    r"""Human-readable name for this app.
    Use a descriptive name like 'Payments API' to identify its purpose.

    """

    slug: str
    r"""Identifies a resource by either its unique ID or its slug.
    Accepts a prefixed ID (such as 'proj_' or 'app_') or a slug.

    """

    git: Optional[AppGitCreateInput] = None
    r"""Connect a GitHub repository to the app on creation. Omit to create the app
    without a repository and connect one later with apps.updateApp.

    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["git"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
