"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from typing_extensions import Annotated, TypedDict
from unkey.py.types import BaseModel


class V2DeployCreateDeploymentResponseDataTypedDict(TypedDict):
    deployment_id: str
    r"""Unique deployment identifier"""


class V2DeployCreateDeploymentResponseData(BaseModel):
    deployment_id: Annotated[str, pydantic.Field(alias="deploymentId")]
    r"""Unique deployment identifier"""


try:
    V2DeployCreateDeploymentResponseData.model_rebuild()
except NameError:
    pass
