"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from typing_extensions import Annotated, TypedDict
from unkey.py.types import BaseModel


class V2DeploymentsCreateDeploymentResponseDataTypedDict(TypedDict):
    deployment_id: str
    r"""Unique deployment identifier. Poll deployments.getDeployment with this id to watch status."""


class V2DeploymentsCreateDeploymentResponseData(BaseModel):
    deployment_id: Annotated[str, pydantic.Field(alias="deploymentId")]
    r"""Unique deployment identifier. Poll deployments.getDeployment with this id to watch status."""


try:
    V2DeploymentsCreateDeploymentResponseData.model_rebuild()
except NameError:
    pass
