"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict
from unkey.py.types import BaseModel, UNSET_SENTINEL


class V2DeploymentsListBuildLogsRequestBodyTypedDict(TypedDict):
    r"""Retrieve the build log entries of a deployment. Get the deployment id from
    `createDeployment` or `listDeployments`.

    """

    deployment_id: str
    r"""Identifies a resource by either its unique ID or its slug.
    Accepts a prefixed ID (such as 'proj_' or 'app_') or a slug.

    """
    step_id: NotRequired[str]
    r"""Return only the log entries of this build step. Use the `stepId` of an
    entry from a previous response. An unknown step returns no entries.
    Omit this field to return the entries of every step.

    """
    cursor: NotRequired[str]
    r"""Pagination cursor from a previous response to fetch the entries after
    it. Omit it to start at the first entry of the build.

    """
    limit: NotRequired[int]
    r"""Maximum number of log entries to return. A response can contain fewer
    entries and still have `hasMore: true` when the entries are large.

    """


class V2DeploymentsListBuildLogsRequestBody(BaseModel):
    r"""Retrieve the build log entries of a deployment. Get the deployment id from
    `createDeployment` or `listDeployments`.

    """

    deployment_id: Annotated[str, pydantic.Field(alias="deploymentId")]
    r"""Identifies a resource by either its unique ID or its slug.
    Accepts a prefixed ID (such as 'proj_' or 'app_') or a slug.

    """

    step_id: Annotated[Optional[str], pydantic.Field(alias="stepId")] = None
    r"""Return only the log entries of this build step. Use the `stepId` of an
    entry from a previous response. An unknown step returns no entries.
    Omit this field to return the entries of every step.

    """

    cursor: Optional[str] = None
    r"""Pagination cursor from a previous response to fetch the entries after
    it. Omit it to start at the first entry of the build.

    """

    limit: Optional[int] = 100
    r"""Maximum number of log entries to return. A response can contain fewer
    entries and still have `hasMore: true` when the entries are large.

    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["stepId", "cursor", "limit"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    V2DeploymentsListBuildLogsRequestBody.model_rebuild()
except NameError:
    pass
