"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .environmentvariableinput import (
    EnvironmentVariableInput,
    EnvironmentVariableInputTypedDict,
)
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict
from unkey.py.types import BaseModel, UNSET_SENTINEL


class V2EnvironmentsSetEnvironmentVariablesRequestBodyTypedDict(TypedDict):
    project: str
    r"""Identifies a resource by either its unique ID or its slug.
    Accepts a prefixed ID (such as 'proj_' or 'app_') or a slug.

    """
    app: str
    r"""Identifies a resource by either its unique ID or its slug.
    Accepts a prefixed ID (such as 'proj_' or 'app_') or a slug.

    """
    environment: str
    r"""Identifies a resource by either its unique ID or its slug.
    Accepts a prefixed ID (such as 'proj_' or 'app_') or a slug.

    """
    variables: List[EnvironmentVariableInputTypedDict]
    r"""The variables to upsert. Each entry is created if its key is new or fully
    overwritten if the key already exists. Existing variables whose keys are
    not in this list are left untouched, unless `prune` is true.

    Each entry is written exactly as sent, never merged with the current
    state. Only `value` is required; omitted optional fields (`kind`,
    `description`) fall back to their defaults rather than any previous value,
    so overwriting a variable without a `description` clears it.

    Each key may appear at most once; a duplicate key is rejected with a 400.
    The whole operation is atomic: if any part fails the environment is left
    unchanged. All values are encrypted at rest. Limited to 50 variables per
    request.

    """
    prune: NotRequired[bool]
    r"""Optional. Defaults to false. When false, the variables above are upserted
    and any existing variable not in the list is kept. When true, this becomes
    a full replace: after upserting, every variable not in the list is deleted.
    Combined with an empty `variables` list, `prune: true` resets the entire
    environment by deleting every variable.
    """


class V2EnvironmentsSetEnvironmentVariablesRequestBody(BaseModel):
    project: str
    r"""Identifies a resource by either its unique ID or its slug.
    Accepts a prefixed ID (such as 'proj_' or 'app_') or a slug.

    """

    app: str
    r"""Identifies a resource by either its unique ID or its slug.
    Accepts a prefixed ID (such as 'proj_' or 'app_') or a slug.

    """

    environment: str
    r"""Identifies a resource by either its unique ID or its slug.
    Accepts a prefixed ID (such as 'proj_' or 'app_') or a slug.

    """

    variables: List[EnvironmentVariableInput]
    r"""The variables to upsert. Each entry is created if its key is new or fully
    overwritten if the key already exists. Existing variables whose keys are
    not in this list are left untouched, unless `prune` is true.

    Each entry is written exactly as sent, never merged with the current
    state. Only `value` is required; omitted optional fields (`kind`,
    `description`) fall back to their defaults rather than any previous value,
    so overwriting a variable without a `description` clears it.

    Each key may appear at most once; a duplicate key is rejected with a 400.
    The whole operation is atomic: if any part fails the environment is left
    unchanged. All values are encrypted at rest. Limited to 50 variables per
    request.

    """

    prune: Optional[bool] = False
    r"""Optional. Defaults to false. When false, the variables above are upserted
    and any existing variable not in the list is kept. When true, this becomes
    a full replace: after upserting, every variable not in the list is deleted.
    Combined with an empty `variables` list, `prune: true` resets the entire
    environment by deleting every variable.
    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["prune"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
