"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict
from unkey.py.types import BaseModel, UNSET_SENTINEL


class V2PortalCreateSessionRequestBodyTypedDict(TypedDict):
    slug: str
    r"""The human-readable slug of the portal configuration to create the session against.
    Identifies which app's portal the end user will access.
    Must be 3-64 characters, lowercase alphanumeric and hyphens only,
    must not start or end with a hyphen, and must not contain consecutive hyphens.

    """
    external_id: str
    r"""The end user's identifier in the customer's system.
    Accepts arbitrary string values (user IDs, emails, UUIDs, etc.).

    """
    permissions: List[str]
    r"""List of RBAC tuple permissions defining what the end user can do in the Portal.
    Each permission is a string in the format `{resourceType}.{resourceId}.{action}`.
    Use `*` as resourceId to grant access to all resources of that type.

    Tab visibility is derived from the action segment:
    - Keys tab: `read_key`, `create_key`, `update_key`, `delete_key`
    - Analytics tab: `read_analytics`
    - Docs tab: visible when any permission is present

    """
    preview: NotRequired[bool]
    r"""When true, creates a preview session for testing the portal experience.

    """


class V2PortalCreateSessionRequestBody(BaseModel):
    slug: str
    r"""The human-readable slug of the portal configuration to create the session against.
    Identifies which app's portal the end user will access.
    Must be 3-64 characters, lowercase alphanumeric and hyphens only,
    must not start or end with a hyphen, and must not contain consecutive hyphens.

    """

    external_id: Annotated[str, pydantic.Field(alias="externalId")]
    r"""The end user's identifier in the customer's system.
    Accepts arbitrary string values (user IDs, emails, UUIDs, etc.).

    """

    permissions: List[str]
    r"""List of RBAC tuple permissions defining what the end user can do in the Portal.
    Each permission is a string in the format `{resourceType}.{resourceId}.{action}`.
    Use `*` as resourceId to grant access to all resources of that type.

    Tab visibility is derived from the action segment:
    - Keys tab: `read_key`, `create_key`, `update_key`, `delete_key`
    - Analytics tab: `read_analytics`
    - Docs tab: visible when any permission is present

    """

    preview: Optional[bool] = False
    r"""When true, creates a preview session for testing the portal experience.

    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["preview"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    V2PortalCreateSessionRequestBody.model_rebuild()
except NameError:
    pass
