"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .v2portallistsessionssession import (
    V2PortalListSessionsSession,
    V2PortalListSessionsSessionTypedDict,
)
import pydantic
from typing import List
from typing_extensions import Annotated, TypedDict
from unkey.py.types import BaseModel


class V2PortalListSessionsResponseDataTypedDict(TypedDict):
    external_id: str
    r"""The end user's identifier, as passed to `portal.createSession`."""
    sessions: List[V2PortalListSessionsSessionTypedDict]
    r"""The end user's revocable sessions, newest first."""


class V2PortalListSessionsResponseData(BaseModel):
    external_id: Annotated[str, pydantic.Field(alias="externalId")]
    r"""The end user's identifier, as passed to `portal.createSession`."""

    sessions: List[V2PortalListSessionsSession]
    r"""The end user's revocable sessions, newest first."""


try:
    V2PortalListSessionsResponseData.model_rebuild()
except NameError:
    pass
