"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from typing_extensions import TypedDict
from unkey.py.types import BaseModel


class V2PortalExchangeCodeRequestBodyTypedDict(TypedDict):
    code: str
    r"""The exchange code carried by the portal URL from `portal.createSession`.
    Must be valid, unexpired, and not previously redeemed.

    """


class V2PortalExchangeCodeRequestBody(BaseModel):
    code: str
    r"""The exchange code carried by the portal URL from `portal.createSession`.
    Must be valid, unexpired, and not previously redeemed.

    """
