"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from typing_extensions import TypedDict
from unkey.py.types import BaseModel


class V2ProjectsGetProjectRequestBodyTypedDict(TypedDict):
    project: str
    r"""Identifies a resource by either its unique ID or its slug.
    Accepts a prefixed ID (such as 'proj_' or 'app_') or a slug.

    """


class V2ProjectsGetProjectRequestBody(BaseModel):
    project: str
    r"""Identifies a resource by either its unique ID or its slug.
    Accepts a prefixed ID (such as 'proj_' or 'app_') or a slug.

    """
