"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .v2ratelimitmultilimitcheck import (
    V2RatelimitMultiLimitCheck,
    V2RatelimitMultiLimitCheckTypedDict,
)
from typing import List
from typing_extensions import TypedDict
from unkey.py.types import BaseModel


class V2RatelimitMultiLimitResponseDataTypedDict(TypedDict):
    r"""Container for multi-limit rate limit check results"""

    passed: bool
    r"""Overall success indicator for all rate limit checks. This is true if ALL individual rate limit checks passed (all have success: true), and false if ANY check failed.

    Use this as a quick indicator to determine if the request should proceed.
    """
    limits: List[V2RatelimitMultiLimitCheckTypedDict]
    r"""Array of individual rate limit check results, one for each rate limit check in the request"""


class V2RatelimitMultiLimitResponseData(BaseModel):
    r"""Container for multi-limit rate limit check results"""

    passed: bool
    r"""Overall success indicator for all rate limit checks. This is true if ALL individual rate limit checks passed (all have success: true), and false if ANY check failed.

    Use this as a quick indicator to determine if the request should proceed.
    """

    limits: List[V2RatelimitMultiLimitCheck]
    r"""Array of individual rate limit check results, one for each rate limit check in the request"""
