"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict
from unkey.py.types import BaseModel, UNSET_SENTINEL


class V2RootKeysListKeysRequestBodyTypedDict(TypedDict):
    limit: NotRequired[int]
    r"""Maximum number of readable root keys per page."""
    cursor: NotRequired[str]
    r"""Opaque cursor from a previous response. Omit for the first page."""


class V2RootKeysListKeysRequestBody(BaseModel):
    limit: Optional[int] = 100
    r"""Maximum number of readable root keys per page."""

    cursor: Optional[str] = None
    r"""Opaque cursor from a previous response. Omit for the first page."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["limit", "cursor"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
