"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .v2workspacegetusageapi import (
    V2WorkspaceGetUsageAPI,
    V2WorkspaceGetUsageAPITypedDict,
)
from .v2workspacegetusagecompute import (
    V2WorkspaceGetUsageCompute,
    V2WorkspaceGetUsageComputeTypedDict,
)
from .v2workspacegetusagegateway import (
    V2WorkspaceGetUsageGateway,
    V2WorkspaceGetUsageGatewayTypedDict,
)
from typing_extensions import TypedDict
from unkey.py.types import BaseModel


class V2WorkspaceGetUsageTotalsTypedDict(TypedDict):
    r"""Workspace totals in the period. `compute` is the sum of
    `breakdowns.byEnvironment[].compute`. `gateway.activeKeys` is the sum of
    `breakdowns.byApp[].gateway.activeKeys`.

    """

    api: V2WorkspaceGetUsageAPITypedDict
    r"""Billable operations through the Unkey API in the period. Key verifications
    through the Unkey gateway are not counted here. The gateway bills by active
    keys, see `gateway`.

    """
    compute: V2WorkspaceGetUsageComputeTypedDict
    r"""Compute usage in the period."""
    gateway: V2WorkspaceGetUsageGatewayTypedDict
    r"""Unkey gateway usage in the period."""


class V2WorkspaceGetUsageTotals(BaseModel):
    r"""Workspace totals in the period. `compute` is the sum of
    `breakdowns.byEnvironment[].compute`. `gateway.activeKeys` is the sum of
    `breakdowns.byApp[].gateway.activeKeys`.

    """

    api: V2WorkspaceGetUsageAPI
    r"""Billable operations through the Unkey API in the period. Key verifications
    through the Unkey gateway are not counted here. The gateway bills by active
    keys, see `gateway`.

    """

    compute: V2WorkspaceGetUsageCompute
    r"""Compute usage in the period."""

    gateway: V2WorkspaceGetUsageGateway
    r"""Unkey gateway usage in the period."""
