"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .v2workspacegetusagerequestperiod import (
    V2WorkspaceGetUsageRequestPeriod,
    V2WorkspaceGetUsageRequestPeriodTypedDict,
)
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict
from unkey.py.types import BaseModel, UNSET_SENTINEL


class V2WorkspaceGetUsageRequestBodyTypedDict(TypedDict):
    period: NotRequired[V2WorkspaceGetUsageRequestPeriodTypedDict]
    r"""The calendar month (UTC) to read. Omit it for the current month to date. A
    past month returns the full month. It cannot be in the future, and it must
    start within the last 90 days, because compute usage is kept for 90 days.

    """


class V2WorkspaceGetUsageRequestBody(BaseModel):
    period: Optional[V2WorkspaceGetUsageRequestPeriod] = None
    r"""The calendar month (UTC) to read. Omit it for the current month to date. A
    past month returns the full month. It cannot be in the future, and it must
    start within the last 90 days, because compute usage is kept for 90 days.

    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["period"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
