"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .v2workspacegetusagecompute import (
    V2WorkspaceGetUsageCompute,
    V2WorkspaceGetUsageComputeTypedDict,
)
from .v2workspacegetusageenvironmentresource import (
    V2WorkspaceGetUsageEnvironmentResource,
    V2WorkspaceGetUsageEnvironmentResourceTypedDict,
)
from .v2workspacegetusageresource import (
    V2WorkspaceGetUsageResource,
    V2WorkspaceGetUsageResourceTypedDict,
)
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict
from unkey.py.types import BaseModel, UNSET_SENTINEL


class V2WorkspaceGetUsageByEnvironmentRowTypedDict(TypedDict):
    r"""Compute one environment used in the period."""

    project: V2WorkspaceGetUsageResourceTypedDict
    r"""The project the environment belongs to."""
    environment: V2WorkspaceGetUsageEnvironmentResourceTypedDict
    r"""An environment. `slug` is omitted when the environment was deleted."""
    compute: V2WorkspaceGetUsageComputeTypedDict
    r"""Compute usage in the period."""
    app: NotRequired[V2WorkspaceGetUsageResourceTypedDict]
    r"""The app the environment belongs to. Omitted when the usage was recorded
    before Unkey stored app ids and the environment was deleted since.

    """


class V2WorkspaceGetUsageByEnvironmentRow(BaseModel):
    r"""Compute one environment used in the period."""

    project: V2WorkspaceGetUsageResource
    r"""The project the environment belongs to."""

    environment: V2WorkspaceGetUsageEnvironmentResource
    r"""An environment. `slug` is omitted when the environment was deleted."""

    compute: V2WorkspaceGetUsageCompute
    r"""Compute usage in the period."""

    app: Optional[V2WorkspaceGetUsageResource] = None
    r"""The app the environment belongs to. Omitted when the usage was recorded
    before Unkey stored app ids and the environment was deleted since.

    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["app"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
