/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { keysAddPermissions } from "../../funcs/keysAddPermissions.js";
import * as components from "../../models/components/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: components.V2KeysAddPermissionsRequestBody$inboundSchema,
};

export const tool$keysAddPermissions: ToolDefinition<typeof args> = {
  name: "keys-add-permissions",
  description: `Add key permissions

Add permissions to a key without affecting existing permissions.

Use this for privilege upgrades, enabling new features, or plan changes that grant additional capabilities. Permissions granted through roles remain unchanged.

**Important**: Changes take effect immediately with up to 30-second edge propagation.

**Required Permissions**

Your root key must have one of the following permissions:
- \`api.*.update_key\` (to update keys in any API)
- \`api.<api_id>.update_key\` (to update keys in a specific API)

**Side Effects**

Invalidates the key cache for immediate effect, and makes permissions available for verification within 30 seconds across all regions.
`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await keysAddPermissions(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
