/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { permissionsGetRole } from "../../funcs/permissionsGetRole.js";
import * as components from "../../models/components/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: components.V2PermissionsGetRoleRequestBody$inboundSchema,
};

export const tool$permissionsGetRole: ToolDefinition<typeof args> = {
  name: "permissions-get-role",
  description: `Get role

Retrieve details about a specific role including its assigned permissions.

**Required Permissions**

Your root key must have the following permission:
- \`rbac.*.read_role\`
`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await permissionsGetRole(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
