"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from .unkeyerror import UnkeyError
from typing import Any, TYPE_CHECKING

from unkey.py.utils.dynamic_imports import lazy_getattr, lazy_dir

if TYPE_CHECKING:
    from .apierror import APIError
    from .badrequesterrorresponse import (
        BadRequestErrorResponse,
        BadRequestErrorResponseData,
    )
    from .conflicterrorresponse import ConflictErrorResponse, ConflictErrorResponseData
    from .forbiddenerrorresponse import (
        ForbiddenErrorResponse,
        ForbiddenErrorResponseData,
    )
    from .goneerrorresponse import GoneErrorResponse, GoneErrorResponseData
    from .internalservererrorresponse import (
        InternalServerErrorResponse,
        InternalServerErrorResponseData,
    )
    from .no_response_error import NoResponseError
    from .notfounderrorresponse import NotFoundErrorResponse, NotFoundErrorResponseData
    from .preconditionfailederrorresponse import (
        PreconditionFailedErrorResponse,
        PreconditionFailedErrorResponseData,
    )
    from .responsevalidationerror import ResponseValidationError
    from .serviceunavailableerrorresponse import (
        ServiceUnavailableErrorResponse,
        ServiceUnavailableErrorResponseData,
    )
    from .toomanyrequestserrorresponse import (
        TooManyRequestsErrorResponse,
        TooManyRequestsErrorResponseData,
    )
    from .unauthorizederrorresponse import (
        UnauthorizedErrorResponse,
        UnauthorizedErrorResponseData,
    )
    from .unprocessableentityerrorresponse import (
        UnprocessableEntityErrorResponse,
        UnprocessableEntityErrorResponseData,
    )

__all__ = [
    "APIError",
    "BadRequestErrorResponse",
    "BadRequestErrorResponseData",
    "ConflictErrorResponse",
    "ConflictErrorResponseData",
    "ForbiddenErrorResponse",
    "ForbiddenErrorResponseData",
    "GoneErrorResponse",
    "GoneErrorResponseData",
    "InternalServerErrorResponse",
    "InternalServerErrorResponseData",
    "NoResponseError",
    "NotFoundErrorResponse",
    "NotFoundErrorResponseData",
    "PreconditionFailedErrorResponse",
    "PreconditionFailedErrorResponseData",
    "ResponseValidationError",
    "ServiceUnavailableErrorResponse",
    "ServiceUnavailableErrorResponseData",
    "TooManyRequestsErrorResponse",
    "TooManyRequestsErrorResponseData",
    "UnauthorizedErrorResponse",
    "UnauthorizedErrorResponseData",
    "UnkeyError",
    "UnprocessableEntityErrorResponse",
    "UnprocessableEntityErrorResponseData",
]

_dynamic_imports: dict[str, str] = {
    "APIError": ".apierror",
    "BadRequestErrorResponse": ".badrequesterrorresponse",
    "BadRequestErrorResponseData": ".badrequesterrorresponse",
    "ConflictErrorResponse": ".conflicterrorresponse",
    "ConflictErrorResponseData": ".conflicterrorresponse",
    "ForbiddenErrorResponse": ".forbiddenerrorresponse",
    "ForbiddenErrorResponseData": ".forbiddenerrorresponse",
    "GoneErrorResponse": ".goneerrorresponse",
    "GoneErrorResponseData": ".goneerrorresponse",
    "InternalServerErrorResponse": ".internalservererrorresponse",
    "InternalServerErrorResponseData": ".internalservererrorresponse",
    "NoResponseError": ".no_response_error",
    "NotFoundErrorResponse": ".notfounderrorresponse",
    "NotFoundErrorResponseData": ".notfounderrorresponse",
    "PreconditionFailedErrorResponse": ".preconditionfailederrorresponse",
    "PreconditionFailedErrorResponseData": ".preconditionfailederrorresponse",
    "ResponseValidationError": ".responsevalidationerror",
    "ServiceUnavailableErrorResponse": ".serviceunavailableerrorresponse",
    "ServiceUnavailableErrorResponseData": ".serviceunavailableerrorresponse",
    "TooManyRequestsErrorResponse": ".toomanyrequestserrorresponse",
    "TooManyRequestsErrorResponseData": ".toomanyrequestserrorresponse",
    "UnauthorizedErrorResponse": ".unauthorizederrorresponse",
    "UnauthorizedErrorResponseData": ".unauthorizederrorresponse",
    "UnprocessableEntityErrorResponse": ".unprocessableentityerrorresponse",
    "UnprocessableEntityErrorResponseData": ".unprocessableentityerrorresponse",
}


def __getattr__(attr_name: str) -> Any:
    return lazy_getattr(
        attr_name, package=__package__, dynamic_imports=_dynamic_imports
    )


def __dir__():
    return lazy_dir(dynamic_imports=_dynamic_imports)
