"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from typing_extensions import Annotated, TypedDict
from unkey_py.types import BaseModel
from unkey_py.utils import FieldMetadata, SecurityMetadata


class SecurityTypedDict(TypedDict):
    root_key: str


class Security(BaseModel):
    root_key: Annotated[
        str,
        FieldMetadata(
            security=SecurityMetadata(
                scheme=True,
                scheme_type="http",
                sub_type="bearer",
                field_name="Authorization",
            )
        ),
    ]
