"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict
from unkey_py.types import BaseModel


class V2RatelimitSetOverrideRequestBodyTypedDict(TypedDict):
    r"""Sets a new or overwrites an existing override."""

    duration: int
    r"""The duration in milliseconds for the rate limit window."""
    identifier: str
    r"""Identifier of your user, this can be their userId, an email, an ip or anything else. Wildcards ( * ) can be used to match multiple identifiers, More info can be found at https://www.unkey.com/docs/ratelimiting/overrides#wildcard-rules"""
    limit: int
    r"""The maximum number of requests allowed."""
    namespace_id: NotRequired[str]
    r"""The id of the namespace. Either namespaceId or namespaceName must be provided"""
    namespace_name: NotRequired[str]
    r"""The name of the namespace. Either namespaceId or namespaceName must be provided"""


class V2RatelimitSetOverrideRequestBody(BaseModel):
    r"""Sets a new or overwrites an existing override."""

    duration: int
    r"""The duration in milliseconds for the rate limit window."""

    identifier: str
    r"""Identifier of your user, this can be their userId, an email, an ip or anything else. Wildcards ( * ) can be used to match multiple identifiers, More info can be found at https://www.unkey.com/docs/ratelimiting/overrides#wildcard-rules"""

    limit: int
    r"""The maximum number of requests allowed."""

    namespace_id: Annotated[Optional[str], pydantic.Field(alias="namespaceId")] = None
    r"""The id of the namespace. Either namespaceId or namespaceName must be provided"""

    namespace_name: Annotated[Optional[str], pydantic.Field(alias="namespaceName")] = (
        None
    )
    r"""The name of the namespace. Either namespaceId or namespaceName must be provided"""
