"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .meta import Meta, MetaTypedDict
from .pagination import Pagination, PaginationTypedDict
from .ratelimitoverride import RatelimitOverride, RatelimitOverrideTypedDict
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict
from unkey_py.types import BaseModel


class V2RatelimitListOverridesResponseBodyTypedDict(TypedDict):
    meta: MetaTypedDict
    data: List[RatelimitOverrideTypedDict]
    pagination: NotRequired[PaginationTypedDict]


class V2RatelimitListOverridesResponseBody(BaseModel):
    meta: Meta

    data: List[RatelimitOverride]

    pagination: Optional[Pagination] = None
