"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .meta import Meta, MetaTypedDict
from .ratelimitdeleteoverrideresponsedata import (
    RatelimitDeleteOverrideResponseData,
    RatelimitDeleteOverrideResponseDataTypedDict,
)
from typing_extensions import TypedDict
from unkey_py.types import BaseModel


class V2RatelimitDeleteOverrideResponseBodyTypedDict(TypedDict):
    meta: MetaTypedDict
    data: RatelimitDeleteOverrideResponseDataTypedDict


class V2RatelimitDeleteOverrideResponseBody(BaseModel):
    meta: Meta

    data: RatelimitDeleteOverrideResponseData
