/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import dotenv from "dotenv";
dotenv.config();
/**
 * Example usage of the @unkey/api SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx apisCreateApi.ts
 */

import { Unkey } from "@unkey/api";

const unkey = new Unkey({
  rootKey: process.env["UNKEY_ROOT_KEY"] ?? "",
});

async function main() {
  const result = await unkey.createApi({
    name: "payment-service-production",
  });

  console.log(result);
}

main().catch(console.error);
