/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  KeyResponseData,
  KeyResponseData$inboundSchema,
  KeyResponseData$Outbound,
  KeyResponseData$outboundSchema,
} from "./keyresponsedata.js";
import {
  Meta,
  Meta$inboundSchema,
  Meta$Outbound,
  Meta$outboundSchema,
} from "./meta.js";
import {
  Pagination,
  Pagination$inboundSchema,
  Pagination$Outbound,
  Pagination$outboundSchema,
} from "./pagination.js";

export type V2ApisListKeysResponseBody = {
  /**
   * Metadata object included in every API response. This provides context about the request and is essential for debugging, audit trails, and support inquiries. The `requestId` is particularly important when troubleshooting issues with the Unkey support team.
   */
  meta: Meta;
  /**
   * Array of API keys with complete configuration and metadata.
   */
  data: Array<KeyResponseData>;
  /**
   * Pagination metadata for list endpoints. Provides information necessary to traverse through large result sets efficiently using cursor-based pagination.
   */
  pagination?: Pagination | undefined;
};

/** @internal */
export const V2ApisListKeysResponseBody$inboundSchema: z.ZodType<
  V2ApisListKeysResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  meta: Meta$inboundSchema,
  data: z.array(KeyResponseData$inboundSchema),
  pagination: Pagination$inboundSchema.optional(),
});
/** @internal */
export type V2ApisListKeysResponseBody$Outbound = {
  meta: Meta$Outbound;
  data: Array<KeyResponseData$Outbound>;
  pagination?: Pagination$Outbound | undefined;
};

/** @internal */
export const V2ApisListKeysResponseBody$outboundSchema: z.ZodType<
  V2ApisListKeysResponseBody$Outbound,
  z.ZodTypeDef,
  V2ApisListKeysResponseBody
> = z.object({
  meta: Meta$outboundSchema,
  data: z.array(KeyResponseData$outboundSchema),
  pagination: Pagination$outboundSchema.optional(),
});

export function v2ApisListKeysResponseBodyToJSON(
  v2ApisListKeysResponseBody: V2ApisListKeysResponseBody,
): string {
  return JSON.stringify(
    V2ApisListKeysResponseBody$outboundSchema.parse(v2ApisListKeysResponseBody),
  );
}
export function v2ApisListKeysResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<V2ApisListKeysResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V2ApisListKeysResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V2ApisListKeysResponseBody' from JSON`,
  );
}
