/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type V2DeployGenerateUploadUrlRequestBody = {
  /**
   * Unkey project ID for which to generate the upload URL
   */
  projectId: string;
};

/** @internal */
export type V2DeployGenerateUploadUrlRequestBody$Outbound = {
  projectId: string;
};

/** @internal */
export const V2DeployGenerateUploadUrlRequestBody$outboundSchema: z.ZodType<
  V2DeployGenerateUploadUrlRequestBody$Outbound,
  z.ZodTypeDef,
  V2DeployGenerateUploadUrlRequestBody
> = z.object({
  projectId: z.string(),
});

export function v2DeployGenerateUploadUrlRequestBodyToJSON(
  v2DeployGenerateUploadUrlRequestBody: V2DeployGenerateUploadUrlRequestBody,
): string {
  return JSON.stringify(
    V2DeployGenerateUploadUrlRequestBody$outboundSchema.parse(
      v2DeployGenerateUploadUrlRequestBody,
    ),
  );
}
