/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  Meta,
  Meta$inboundSchema,
  Meta$Outbound,
  Meta$outboundSchema,
} from "./meta.js";
import {
  V2PermissionsGetRoleResponseData,
  V2PermissionsGetRoleResponseData$inboundSchema,
  V2PermissionsGetRoleResponseData$Outbound,
  V2PermissionsGetRoleResponseData$outboundSchema,
} from "./v2permissionsgetroleresponsedata.js";

export type V2PermissionsGetRoleResponseBody = {
  /**
   * Metadata object included in every API response. This provides context about the request and is essential for debugging, audit trails, and support inquiries. The `requestId` is particularly important when troubleshooting issues with the Unkey support team.
   */
  meta: Meta;
  /**
   * Complete role details including assigned permissions.
   */
  data: V2PermissionsGetRoleResponseData;
};

/** @internal */
export const V2PermissionsGetRoleResponseBody$inboundSchema: z.ZodType<
  V2PermissionsGetRoleResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  meta: Meta$inboundSchema,
  data: V2PermissionsGetRoleResponseData$inboundSchema,
});

/** @internal */
export type V2PermissionsGetRoleResponseBody$Outbound = {
  meta: Meta$Outbound;
  data: V2PermissionsGetRoleResponseData$Outbound;
};

/** @internal */
export const V2PermissionsGetRoleResponseBody$outboundSchema: z.ZodType<
  V2PermissionsGetRoleResponseBody$Outbound,
  z.ZodTypeDef,
  V2PermissionsGetRoleResponseBody
> = z.object({
  meta: Meta$outboundSchema,
  data: V2PermissionsGetRoleResponseData$outboundSchema,
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V2PermissionsGetRoleResponseBody$ {
  /** @deprecated use `V2PermissionsGetRoleResponseBody$inboundSchema` instead. */
  export const inboundSchema = V2PermissionsGetRoleResponseBody$inboundSchema;
  /** @deprecated use `V2PermissionsGetRoleResponseBody$outboundSchema` instead. */
  export const outboundSchema = V2PermissionsGetRoleResponseBody$outboundSchema;
  /** @deprecated use `V2PermissionsGetRoleResponseBody$Outbound` instead. */
  export type Outbound = V2PermissionsGetRoleResponseBody$Outbound;
}

export function v2PermissionsGetRoleResponseBodyToJSON(
  v2PermissionsGetRoleResponseBody: V2PermissionsGetRoleResponseBody,
): string {
  return JSON.stringify(
    V2PermissionsGetRoleResponseBody$outboundSchema.parse(
      v2PermissionsGetRoleResponseBody,
    ),
  );
}

export function v2PermissionsGetRoleResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<V2PermissionsGetRoleResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V2PermissionsGetRoleResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V2PermissionsGetRoleResponseBody' from JSON`,
  );
}
