// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/unkeyed/sdks/api/go/v2/internal/utils"
	"github.com/unkeyed/sdks/api/go/v2/models/components"
)

type ApisCreateAPIResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// API namespace created successfully. The response contains the unique API ID for referencing this namespace in key operations.
	//
	V2ApisCreateAPIResponseBody *components.V2ApisCreateAPIResponseBody
}

func (a ApisCreateAPIResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *ApisCreateAPIResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *ApisCreateAPIResponse) GetHTTPMeta() components.HTTPMetadata {
	if a == nil {
		return components.HTTPMetadata{}
	}
	return a.HTTPMeta
}

func (a *ApisCreateAPIResponse) GetV2ApisCreateAPIResponseBody() *components.V2ApisCreateAPIResponseBody {
	if a == nil {
		return nil
	}
	return a.V2ApisCreateAPIResponseBody
}
