// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/unkeyed/sdks/api/go/v2/models/components"
)

type ApisListKeysResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successfully retrieved paginated keys. Use the pagination cursor for additional results when `hasMore: true`.
	//
	V2ApisListKeysResponseBody *components.V2ApisListKeysResponseBody
}

func (a *ApisListKeysResponse) GetHTTPMeta() components.HTTPMetadata {
	if a == nil {
		return components.HTTPMetadata{}
	}
	return a.HTTPMeta
}

func (a *ApisListKeysResponse) GetV2ApisListKeysResponseBody() *components.V2ApisListKeysResponseBody {
	if a == nil {
		return nil
	}
	return a.V2ApisListKeysResponseBody
}
