// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/unkeyed/sdks/api/go/v2/internal/utils"
	"github.com/unkeyed/sdks/api/go/v2/models/components"
)

type AppsGetAppResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successfully retrieved the app.
	//
	V2AppsGetAppResponseBody *components.V2AppsGetAppResponseBody
}

func (a AppsGetAppResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AppsGetAppResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AppsGetAppResponse) GetHTTPMeta() components.HTTPMetadata {
	if a == nil {
		return components.HTTPMetadata{}
	}
	return a.HTTPMeta
}

func (a *AppsGetAppResponse) GetV2AppsGetAppResponseBody() *components.V2AppsGetAppResponseBody {
	if a == nil {
		return nil
	}
	return a.V2AppsGetAppResponseBody
}
