// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/unkeyed/sdks/api/go/v2/models/components"
)

type DeleteKeyResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Key deleted successfully. Verification fails immediately with up to 30-second edge propagation.
	//
	V2KeysDeleteKeyResponseBody *components.V2KeysDeleteKeyResponseBody
}

func (o *DeleteKeyResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *DeleteKeyResponse) GetV2KeysDeleteKeyResponseBody() *components.V2KeysDeleteKeyResponseBody {
	if o == nil {
		return nil
	}
	return o.V2KeysDeleteKeyResponseBody
}
