// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/unkeyed/sdks/api/go/v2/internal/utils"
	"github.com/unkeyed/sdks/api/go/v2/models/components"
)

type DeploymentsCreateDeploymentResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Deployment created successfully
	V2DeploymentsCreateDeploymentResponseBody *components.V2DeploymentsCreateDeploymentResponseBody
}

func (d DeploymentsCreateDeploymentResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DeploymentsCreateDeploymentResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DeploymentsCreateDeploymentResponse) GetHTTPMeta() components.HTTPMetadata {
	if d == nil {
		return components.HTTPMetadata{}
	}
	return d.HTTPMeta
}

func (d *DeploymentsCreateDeploymentResponse) GetV2DeploymentsCreateDeploymentResponseBody() *components.V2DeploymentsCreateDeploymentResponseBody {
	if d == nil {
		return nil
	}
	return d.V2DeploymentsCreateDeploymentResponseBody
}
