// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/unkeyed/sdks/api/go/v2/internal/utils"
	"github.com/unkeyed/sdks/api/go/v2/models/components"
)

type DeploymentsStartDeploymentResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Start accepted and enqueued. The deployment transitions to `ready`
	// asynchronously; poll `getDeployment` to observe the transition.
	//
	V2DeploymentsStartDeploymentResponseBody *components.V2DeploymentsStartDeploymentResponseBody
}

func (d DeploymentsStartDeploymentResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DeploymentsStartDeploymentResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DeploymentsStartDeploymentResponse) GetHTTPMeta() components.HTTPMetadata {
	if d == nil {
		return components.HTTPMetadata{}
	}
	return d.HTTPMeta
}

func (d *DeploymentsStartDeploymentResponse) GetV2DeploymentsStartDeploymentResponseBody() *components.V2DeploymentsStartDeploymentResponseBody {
	if d == nil {
		return nil
	}
	return d.V2DeploymentsStartDeploymentResponseBody
}
