// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/unkeyed/sdks/api/go/v2/internal/utils"
	"github.com/unkeyed/sdks/api/go/v2/models/components"
)

type DeployGetDeploymentResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Deployment retrieved successfully
	V2DeployGetDeploymentResponseBody *components.V2DeployGetDeploymentResponseBody
}

func (d DeployGetDeploymentResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DeployGetDeploymentResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DeployGetDeploymentResponse) GetHTTPMeta() components.HTTPMetadata {
	if d == nil {
		return components.HTTPMetadata{}
	}
	return d.HTTPMeta
}

func (d *DeployGetDeploymentResponse) GetV2DeployGetDeploymentResponseBody() *components.V2DeployGetDeploymentResponseBody {
	if d == nil {
		return nil
	}
	return d.V2DeployGetDeploymentResponseBody
}
