// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/unkeyed/sdks/api/go/v2/internal/utils"
	"github.com/unkeyed/sdks/api/go/v2/models/components"
)

type IdentitiesListIdentitiesResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successfully retrieved the list of identities
	V2IdentitiesListIdentitiesResponseBody *components.V2IdentitiesListIdentitiesResponseBody

	Next func() (*IdentitiesListIdentitiesResponse, error)
}

func (i IdentitiesListIdentitiesResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *IdentitiesListIdentitiesResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (i *IdentitiesListIdentitiesResponse) GetHTTPMeta() components.HTTPMetadata {
	if i == nil {
		return components.HTTPMetadata{}
	}
	return i.HTTPMeta
}

func (i *IdentitiesListIdentitiesResponse) GetV2IdentitiesListIdentitiesResponseBody() *components.V2IdentitiesListIdentitiesResponseBody {
	if i == nil {
		return nil
	}
	return i.V2IdentitiesListIdentitiesResponseBody
}
