// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/unkeyed/sdks/api/go/v2/internal/utils"
	"github.com/unkeyed/sdks/api/go/v2/models/components"
)

type KeysSetPermissionsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Permissions set successfully. Returns all permissions currently assigned to the key.
	V2KeysSetPermissionsResponseBody *components.V2KeysSetPermissionsResponseBody
}

func (k KeysSetPermissionsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(k, "", false)
}

func (k *KeysSetPermissionsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &k, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (k *KeysSetPermissionsResponse) GetHTTPMeta() components.HTTPMetadata {
	if k == nil {
		return components.HTTPMetadata{}
	}
	return k.HTTPMeta
}

func (k *KeysSetPermissionsResponse) GetV2KeysSetPermissionsResponseBody() *components.V2KeysSetPermissionsResponseBody {
	if k == nil {
		return nil
	}
	return k.V2KeysSetPermissionsResponseBody
}
