// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/unkeyed/sdks/api/go/v2/internal/utils"
	"github.com/unkeyed/sdks/api/go/v2/models/components"
)

type KeysSetRolesResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Roles set successfully. Returns all roles currently assigned to the key.
	V2KeysSetRolesResponseBody *components.V2KeysSetRolesResponseBody
}

func (k KeysSetRolesResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(k, "", false)
}

func (k *KeysSetRolesResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &k, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (k *KeysSetRolesResponse) GetHTTPMeta() components.HTTPMetadata {
	if k == nil {
		return components.HTTPMetadata{}
	}
	return k.HTTPMeta
}

func (k *KeysSetRolesResponse) GetV2KeysSetRolesResponseBody() *components.V2KeysSetRolesResponseBody {
	if k == nil {
		return nil
	}
	return k.V2KeysSetRolesResponseBody
}
