// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/unkeyed/sdks/api/go/v2/internal/utils"
	"github.com/unkeyed/sdks/api/go/v2/models/components"
)

type KeysCreateKeyResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successfully created a new API key. The response includes both the keyId (for reference in your system) and the full key string. IMPORTANT: This is the only time the complete key is available - it cannot be retrieved later. You must securely provide this key to your end user immediately.
	V2KeysCreateKeyResponseBody *components.V2KeysCreateKeyResponseBody
}

func (k KeysCreateKeyResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(k, "", false)
}

func (k *KeysCreateKeyResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &k, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (k *KeysCreateKeyResponse) GetHTTPMeta() components.HTTPMetadata {
	if k == nil {
		return components.HTTPMetadata{}
	}
	return k.HTTPMeta
}

func (k *KeysCreateKeyResponse) GetV2KeysCreateKeyResponseBody() *components.V2KeysCreateKeyResponseBody {
	if k == nil {
		return nil
	}
	return k.V2KeysCreateKeyResponseBody
}
