// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/unkeyed/sdks/api/go/v2/internal/utils"
	"github.com/unkeyed/sdks/api/go/v2/models/components"
)

type KeysUpdateKeyResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Key updated successfully. Changes take effect immediately with up to 30-second edge propagation.
	//
	V2KeysUpdateKeyResponseBody *components.V2KeysUpdateKeyResponseBody
}

func (k KeysUpdateKeyResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(k, "", false)
}

func (k *KeysUpdateKeyResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &k, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (k *KeysUpdateKeyResponse) GetHTTPMeta() components.HTTPMetadata {
	if k == nil {
		return components.HTTPMetadata{}
	}
	return k.HTTPMeta
}

func (k *KeysUpdateKeyResponse) GetV2KeysUpdateKeyResponseBody() *components.V2KeysUpdateKeyResponseBody {
	if k == nil {
		return nil
	}
	return k.V2KeysUpdateKeyResponseBody
}
