// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/unkeyed/sdks/api/go/v2/models/components"
)

type KeysAddRolesResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Roles added successfully. Returns all roles currently assigned to the key.
	V2KeysAddRolesResponseBody *components.V2KeysAddRolesResponseBody
}

func (k *KeysAddRolesResponse) GetHTTPMeta() components.HTTPMetadata {
	if k == nil {
		return components.HTTPMetadata{}
	}
	return k.HTTPMeta
}

func (k *KeysAddRolesResponse) GetV2KeysAddRolesResponseBody() *components.V2KeysAddRolesResponseBody {
	if k == nil {
		return nil
	}
	return k.V2KeysAddRolesResponseBody
}
