// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/unkeyed/sdks/api/go/v2/internal/utils"
	"github.com/unkeyed/sdks/api/go/v2/models/components"
)

type PermissionsCreateRoleResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Role created successfully
	V2PermissionsCreateRoleResponseBody *components.V2PermissionsCreateRoleResponseBody
}

func (p PermissionsCreateRoleResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PermissionsCreateRoleResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PermissionsCreateRoleResponse) GetHTTPMeta() components.HTTPMetadata {
	if p == nil {
		return components.HTTPMetadata{}
	}
	return p.HTTPMeta
}

func (p *PermissionsCreateRoleResponse) GetV2PermissionsCreateRoleResponseBody() *components.V2PermissionsCreateRoleResponseBody {
	if p == nil {
		return nil
	}
	return p.V2PermissionsCreateRoleResponseBody
}
