// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/unkeyed/sdks/api/go/v2/internal/utils"
	"github.com/unkeyed/sdks/api/go/v2/models/components"
)

type PortalGetVerificationsSecurity struct {
	PortalSession string `security:"scheme,type=apiKey,subtype=cookie,name=portal_session,env=unkey_portal_session"`
}

func (p *PortalGetVerificationsSecurity) GetPortalSession() string {
	if p == nil {
		return ""
	}
	return p.PortalSession
}

type PortalGetVerificationsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successfully retrieved verification analytics.
	//
	V2PortalGetVerificationsResponseBody *components.V2PortalGetVerificationsResponseBody
}

func (p PortalGetVerificationsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PortalGetVerificationsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PortalGetVerificationsResponse) GetHTTPMeta() components.HTTPMetadata {
	if p == nil {
		return components.HTTPMetadata{}
	}
	return p.HTTPMeta
}

func (p *PortalGetVerificationsResponse) GetV2PortalGetVerificationsResponseBody() *components.V2PortalGetVerificationsResponseBody {
	if p == nil {
		return nil
	}
	return p.V2PortalGetVerificationsResponseBody
}
