// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/unkeyed/sdks/api/go/v2/models/components"
)

type PortalExchangeSessionResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Session exchanged successfully. Use the returned token for subsequent API calls.
	//
	V2PortalExchangeSessionResponseBody *components.V2PortalExchangeSessionResponseBody
	Headers                             map[string][]string
}

func (p *PortalExchangeSessionResponse) GetHTTPMeta() components.HTTPMetadata {
	if p == nil {
		return components.HTTPMetadata{}
	}
	return p.HTTPMeta
}

func (p *PortalExchangeSessionResponse) GetV2PortalExchangeSessionResponseBody() *components.V2PortalExchangeSessionResponseBody {
	if p == nil {
		return nil
	}
	return p.V2PortalExchangeSessionResponseBody
}

func (p *PortalExchangeSessionResponse) GetHeaders() map[string][]string {
	if p == nil {
		return map[string][]string{}
	}
	return p.Headers
}
