// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/unkeyed/sdks/api/go/v2/internal/utils"
	"github.com/unkeyed/sdks/api/go/v2/models/components"
)

type ProjectsUpdateProjectResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successfully updated the project.
	//
	V2ProjectsUpdateProjectResponseBody *components.V2ProjectsUpdateProjectResponseBody
}

func (p ProjectsUpdateProjectResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *ProjectsUpdateProjectResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *ProjectsUpdateProjectResponse) GetHTTPMeta() components.HTTPMetadata {
	if p == nil {
		return components.HTTPMetadata{}
	}
	return p.HTTPMeta
}

func (p *ProjectsUpdateProjectResponse) GetV2ProjectsUpdateProjectResponseBody() *components.V2ProjectsUpdateProjectResponseBody {
	if p == nil {
		return nil
	}
	return p.V2ProjectsUpdateProjectResponseBody
}
