// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/unkeyed/sdks/api/go/v3/internal/utils"
	"github.com/unkeyed/sdks/api/go/v3/models/components"
)

type RootKeysRerollKeyResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Root key rerolled. Save the secret now; it cannot be retrieved later.
	V2RootKeysRerollKeyResponseBody *components.V2RootKeysRerollKeyResponseBody
}

func (r RootKeysRerollKeyResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *RootKeysRerollKeyResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (r *RootKeysRerollKeyResponse) GetHTTPMeta() components.HTTPMetadata {
	if r == nil {
		return components.HTTPMetadata{}
	}
	return r.HTTPMeta
}

func (r *RootKeysRerollKeyResponse) GetV2RootKeysRerollKeyResponseBody() *components.V2RootKeysRerollKeyResponseBody {
	if r == nil {
		return nil
	}
	return r.V2RootKeysRerollKeyResponseBody
}
