// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/unkeyed/sdks/api/go/v2/models/components"
)

type WhoamiResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successfully retrieved key information.
	//
	V2KeysWhoamiResponseBody *components.V2KeysWhoamiResponseBody
}

func (w *WhoamiResponse) GetHTTPMeta() components.HTTPMetadata {
	if w == nil {
		return components.HTTPMetadata{}
	}
	return w.HTTPMeta
}

func (w *WhoamiResponse) GetV2KeysWhoamiResponseBody() *components.V2KeysWhoamiResponseBody {
	if w == nil {
		return nil
	}
	return w.V2KeysWhoamiResponseBody
}
