name: Publish API-GO
permissions:
  checks: write
  contents: write
  pull-requests: write
  statuses: write
  id-token: write
"on":
  push:
    branches:
      - main
    paths:
      - api/go/.speakeasy/gen.lock
  workflow_dispatch: {}
jobs:
  publish:
    uses: speakeasy-api/sdk-generation-action/.github/workflows/sdk-publish.yaml@v15
    with:
      target: api-go
    secrets:
      github_access_token: ${{ secrets.GITHUB_TOKEN }}
      slack_webhook_url: ${{secrets.SLACK_WEBHOOK_URL}}
      speakeasy_api_key: ${{ secrets.SPEAKEASY_API_KEY }}
